package com.ticnow.security.model.admin;

public class Actions {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTIONS.id_actions
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id_actions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTIONS.actions_available
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String actions_available;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTIONS.action_code
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String action_code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTIONS.id_actions
     *
     * @return the value of ACTIONS.id_actions
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId_actions() {
        return id_actions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTIONS.id_actions
     *
     * @param id_actions the value for ACTIONS.id_actions
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId_actions(Integer id_actions) {
        this.id_actions = id_actions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTIONS.actions_available
     *
     * @return the value of ACTIONS.actions_available
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getActions_available() {
        return actions_available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTIONS.actions_available
     *
     * @param actions_available the value for ACTIONS.actions_available
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setActions_available(String actions_available) {
        this.actions_available = actions_available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTIONS.action_code
     *
     * @return the value of ACTIONS.action_code
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getAction_code() {
        return action_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTIONS.action_code
     *
     * @param action_code the value for ACTIONS.action_code
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setAction_code(String action_code) {
        this.action_code = action_code;
    }
}