package com.ticnow.security.model.admin;

public class Alerts {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALERTS.id_alert
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id_alert;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALERTS.id_alert_type
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id_alert_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALERTS.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALERTS.alerts_identifier
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String alerts_identifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALERTS.dispatch_channel
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String dispatch_channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALERTS.send_type
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Boolean send_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALERTS.daily_summary
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Boolean daily_summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALERTS.summary_detail
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String summary_detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALERTS.state
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALERTS.id_alert
     *
     * @return the value of ALERTS.id_alert
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId_alert() {
        return id_alert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALERTS.id_alert
     *
     * @param id_alert the value for ALERTS.id_alert
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId_alert(Integer id_alert) {
        this.id_alert = id_alert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALERTS.id_alert_type
     *
     * @return the value of ALERTS.id_alert_type
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId_alert_type() {
        return id_alert_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALERTS.id_alert_type
     *
     * @param id_alert_type the value for ALERTS.id_alert_type
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId_alert_type(Integer id_alert_type) {
        this.id_alert_type = id_alert_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALERTS.id
     *
     * @return the value of ALERTS.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALERTS.id
     *
     * @param id the value for ALERTS.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALERTS.alerts_identifier
     *
     * @return the value of ALERTS.alerts_identifier
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getAlerts_identifier() {
        return alerts_identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALERTS.alerts_identifier
     *
     * @param alerts_identifier the value for ALERTS.alerts_identifier
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setAlerts_identifier(String alerts_identifier) {
        this.alerts_identifier = alerts_identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALERTS.dispatch_channel
     *
     * @return the value of ALERTS.dispatch_channel
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getDispatch_channel() {
        return dispatch_channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALERTS.dispatch_channel
     *
     * @param dispatch_channel the value for ALERTS.dispatch_channel
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setDispatch_channel(String dispatch_channel) {
        this.dispatch_channel = dispatch_channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALERTS.send_type
     *
     * @return the value of ALERTS.send_type
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Boolean getSend_type() {
        return send_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALERTS.send_type
     *
     * @param send_type the value for ALERTS.send_type
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setSend_type(Boolean send_type) {
        this.send_type = send_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALERTS.daily_summary
     *
     * @return the value of ALERTS.daily_summary
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Boolean getDaily_summary() {
        return daily_summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALERTS.daily_summary
     *
     * @param daily_summary the value for ALERTS.daily_summary
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setDaily_summary(Boolean daily_summary) {
        this.daily_summary = daily_summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALERTS.summary_detail
     *
     * @return the value of ALERTS.summary_detail
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getSummary_detail() {
        return summary_detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALERTS.summary_detail
     *
     * @param summary_detail the value for ALERTS.summary_detail
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setSummary_detail(String summary_detail) {
        this.summary_detail = summary_detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALERTS.state
     *
     * @return the value of ALERTS.state
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALERTS.state
     *
     * @param state the value for ALERTS.state
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setState(String state) {
        this.state = state;
    }
}