package com.ticnow.security.model.admin;

public class AlertSubtype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALERT_SUBTYPE.id_alert_subtype
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id_alert_subtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ALERT_SUBTYPE.alert_subtype_name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String alert_subtype_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALERT_SUBTYPE.id_alert_subtype
     *
     * @return the value of ALERT_SUBTYPE.id_alert_subtype
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId_alert_subtype() {
        return id_alert_subtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALERT_SUBTYPE.id_alert_subtype
     *
     * @param id_alert_subtype the value for ALERT_SUBTYPE.id_alert_subtype
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId_alert_subtype(Integer id_alert_subtype) {
        this.id_alert_subtype = id_alert_subtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALERT_SUBTYPE.alert_subtype_name
     *
     * @return the value of ALERT_SUBTYPE.alert_subtype_name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getAlert_subtype_name() {
        return alert_subtype_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALERT_SUBTYPE.alert_subtype_name
     *
     * @param alert_subtype_name the value for ALERT_SUBTYPE.alert_subtype_name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setAlert_subtype_name(String alert_subtype_name) {
        this.alert_subtype_name = alert_subtype_name;
    }
}