package com.ticnow.security.model.admin;

public class AnalizeTransactionDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ANALIZE_TRANSACTION_DETAIL.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ANALIZE_TRANSACTION_DETAIL.uuid
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ANALIZE_TRANSACTION_DETAIL.subTypeTransaction
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String subTypeTransaction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ANALIZE_TRANSACTION_DETAIL.transaction_detail_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer transaction_detail_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ANALIZE_TRANSACTION_DETAIL.riskScore
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String riskScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ANALIZE_TRANSACTION_DETAIL.actionType
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String actionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ANALIZE_TRANSACTION_DETAIL.reResponse
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String reResponse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ANALIZE_TRANSACTION_DETAIL.deviceFingerPrint
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String deviceFingerPrint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ANALIZE_TRANSACTION_DETAIL.deviceTokenCookie
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String deviceTokenCookie;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ANALIZE_TRANSACTION_DETAIL.request
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String request;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ANALIZE_TRANSACTION_DETAIL.id
     *
     * @return the value of ANALIZE_TRANSACTION_DETAIL.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ANALIZE_TRANSACTION_DETAIL.id
     *
     * @param id the value for ANALIZE_TRANSACTION_DETAIL.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ANALIZE_TRANSACTION_DETAIL.uuid
     *
     * @return the value of ANALIZE_TRANSACTION_DETAIL.uuid
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ANALIZE_TRANSACTION_DETAIL.uuid
     *
     * @param uuid the value for ANALIZE_TRANSACTION_DETAIL.uuid
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ANALIZE_TRANSACTION_DETAIL.subTypeTransaction
     *
     * @return the value of ANALIZE_TRANSACTION_DETAIL.subTypeTransaction
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getSubTypeTransaction() {
        return subTypeTransaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ANALIZE_TRANSACTION_DETAIL.subTypeTransaction
     *
     * @param subTypeTransaction the value for ANALIZE_TRANSACTION_DETAIL.subTypeTransaction
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setSubTypeTransaction(String subTypeTransaction) {
        this.subTypeTransaction = subTypeTransaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ANALIZE_TRANSACTION_DETAIL.transaction_detail_id
     *
     * @return the value of ANALIZE_TRANSACTION_DETAIL.transaction_detail_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getTransaction_detail_id() {
        return transaction_detail_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ANALIZE_TRANSACTION_DETAIL.transaction_detail_id
     *
     * @param transaction_detail_id the value for ANALIZE_TRANSACTION_DETAIL.transaction_detail_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setTransaction_detail_id(Integer transaction_detail_id) {
        this.transaction_detail_id = transaction_detail_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ANALIZE_TRANSACTION_DETAIL.riskScore
     *
     * @return the value of ANALIZE_TRANSACTION_DETAIL.riskScore
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getRiskScore() {
        return riskScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ANALIZE_TRANSACTION_DETAIL.riskScore
     *
     * @param riskScore the value for ANALIZE_TRANSACTION_DETAIL.riskScore
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setRiskScore(String riskScore) {
        this.riskScore = riskScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ANALIZE_TRANSACTION_DETAIL.actionType
     *
     * @return the value of ANALIZE_TRANSACTION_DETAIL.actionType
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getActionType() {
        return actionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ANALIZE_TRANSACTION_DETAIL.actionType
     *
     * @param actionType the value for ANALIZE_TRANSACTION_DETAIL.actionType
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setActionType(String actionType) {
        this.actionType = actionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ANALIZE_TRANSACTION_DETAIL.reResponse
     *
     * @return the value of ANALIZE_TRANSACTION_DETAIL.reResponse
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getReResponse() {
        return reResponse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ANALIZE_TRANSACTION_DETAIL.reResponse
     *
     * @param reResponse the value for ANALIZE_TRANSACTION_DETAIL.reResponse
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setReResponse(String reResponse) {
        this.reResponse = reResponse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ANALIZE_TRANSACTION_DETAIL.deviceFingerPrint
     *
     * @return the value of ANALIZE_TRANSACTION_DETAIL.deviceFingerPrint
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getDeviceFingerPrint() {
        return deviceFingerPrint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ANALIZE_TRANSACTION_DETAIL.deviceFingerPrint
     *
     * @param deviceFingerPrint the value for ANALIZE_TRANSACTION_DETAIL.deviceFingerPrint
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setDeviceFingerPrint(String deviceFingerPrint) {
        this.deviceFingerPrint = deviceFingerPrint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ANALIZE_TRANSACTION_DETAIL.deviceTokenCookie
     *
     * @return the value of ANALIZE_TRANSACTION_DETAIL.deviceTokenCookie
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getDeviceTokenCookie() {
        return deviceTokenCookie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ANALIZE_TRANSACTION_DETAIL.deviceTokenCookie
     *
     * @param deviceTokenCookie the value for ANALIZE_TRANSACTION_DETAIL.deviceTokenCookie
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setDeviceTokenCookie(String deviceTokenCookie) {
        this.deviceTokenCookie = deviceTokenCookie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ANALIZE_TRANSACTION_DETAIL.request
     *
     * @return the value of ANALIZE_TRANSACTION_DETAIL.request
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getRequest() {
        return request;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ANALIZE_TRANSACTION_DETAIL.request
     *
     * @param request the value for ANALIZE_TRANSACTION_DETAIL.request
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setRequest(String request) {
        this.request = request;
    }
}