package com.ticnow.security.model.admin;

import java.math.BigDecimal;

public class AnalizeTransaction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ANALIZE_TRANSACTION.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ANALIZE_TRANSACTION.transactionType
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String transactionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ANALIZE_TRANSACTION.transactionName
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String transactionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ANALIZE_TRANSACTION.channel
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ANALIZE_TRANSACTION.app
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String app;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ANALIZE_TRANSACTION.userId
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ANALIZE_TRANSACTION.deviceId
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ANALIZE_TRANSACTION.deviceFingerPrint
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String deviceFingerPrint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ANALIZE_TRANSACTION.location
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ANALIZE_TRANSACTION.forwaredIp
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String forwaredIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ANALIZE_TRANSACTION.userAgent
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String userAgent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ANALIZE_TRANSACTION.transactionHash
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String transactionHash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ANALIZE_TRANSACTION.biometricDetail
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String biometricDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ANALIZE_TRANSACTION.transactionDetailId
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer transactionDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ANALIZE_TRANSACTION.currentMillis
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private BigDecimal currentMillis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ANALIZE_TRANSACTION.status
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ANALIZE_TRANSACTION.uuid
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ANALIZE_TRANSACTION.httpRefer
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String httpRefer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ANALIZE_TRANSACTION.id
     *
     * @return the value of ANALIZE_TRANSACTION.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ANALIZE_TRANSACTION.id
     *
     * @param id the value for ANALIZE_TRANSACTION.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ANALIZE_TRANSACTION.transactionType
     *
     * @return the value of ANALIZE_TRANSACTION.transactionType
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getTransactionType() {
        return transactionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ANALIZE_TRANSACTION.transactionType
     *
     * @param transactionType the value for ANALIZE_TRANSACTION.transactionType
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ANALIZE_TRANSACTION.transactionName
     *
     * @return the value of ANALIZE_TRANSACTION.transactionName
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getTransactionName() {
        return transactionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ANALIZE_TRANSACTION.transactionName
     *
     * @param transactionName the value for ANALIZE_TRANSACTION.transactionName
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setTransactionName(String transactionName) {
        this.transactionName = transactionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ANALIZE_TRANSACTION.channel
     *
     * @return the value of ANALIZE_TRANSACTION.channel
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ANALIZE_TRANSACTION.channel
     *
     * @param channel the value for ANALIZE_TRANSACTION.channel
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setChannel(String channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ANALIZE_TRANSACTION.app
     *
     * @return the value of ANALIZE_TRANSACTION.app
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getApp() {
        return app;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ANALIZE_TRANSACTION.app
     *
     * @param app the value for ANALIZE_TRANSACTION.app
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setApp(String app) {
        this.app = app;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ANALIZE_TRANSACTION.userId
     *
     * @return the value of ANALIZE_TRANSACTION.userId
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ANALIZE_TRANSACTION.userId
     *
     * @param userId the value for ANALIZE_TRANSACTION.userId
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ANALIZE_TRANSACTION.deviceId
     *
     * @return the value of ANALIZE_TRANSACTION.deviceId
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ANALIZE_TRANSACTION.deviceId
     *
     * @param deviceId the value for ANALIZE_TRANSACTION.deviceId
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ANALIZE_TRANSACTION.deviceFingerPrint
     *
     * @return the value of ANALIZE_TRANSACTION.deviceFingerPrint
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getDeviceFingerPrint() {
        return deviceFingerPrint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ANALIZE_TRANSACTION.deviceFingerPrint
     *
     * @param deviceFingerPrint the value for ANALIZE_TRANSACTION.deviceFingerPrint
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setDeviceFingerPrint(String deviceFingerPrint) {
        this.deviceFingerPrint = deviceFingerPrint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ANALIZE_TRANSACTION.location
     *
     * @return the value of ANALIZE_TRANSACTION.location
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ANALIZE_TRANSACTION.location
     *
     * @param location the value for ANALIZE_TRANSACTION.location
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ANALIZE_TRANSACTION.forwaredIp
     *
     * @return the value of ANALIZE_TRANSACTION.forwaredIp
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getForwaredIp() {
        return forwaredIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ANALIZE_TRANSACTION.forwaredIp
     *
     * @param forwaredIp the value for ANALIZE_TRANSACTION.forwaredIp
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setForwaredIp(String forwaredIp) {
        this.forwaredIp = forwaredIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ANALIZE_TRANSACTION.userAgent
     *
     * @return the value of ANALIZE_TRANSACTION.userAgent
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getUserAgent() {
        return userAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ANALIZE_TRANSACTION.userAgent
     *
     * @param userAgent the value for ANALIZE_TRANSACTION.userAgent
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ANALIZE_TRANSACTION.transactionHash
     *
     * @return the value of ANALIZE_TRANSACTION.transactionHash
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getTransactionHash() {
        return transactionHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ANALIZE_TRANSACTION.transactionHash
     *
     * @param transactionHash the value for ANALIZE_TRANSACTION.transactionHash
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setTransactionHash(String transactionHash) {
        this.transactionHash = transactionHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ANALIZE_TRANSACTION.biometricDetail
     *
     * @return the value of ANALIZE_TRANSACTION.biometricDetail
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getBiometricDetail() {
        return biometricDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ANALIZE_TRANSACTION.biometricDetail
     *
     * @param biometricDetail the value for ANALIZE_TRANSACTION.biometricDetail
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setBiometricDetail(String biometricDetail) {
        this.biometricDetail = biometricDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ANALIZE_TRANSACTION.transactionDetailId
     *
     * @return the value of ANALIZE_TRANSACTION.transactionDetailId
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getTransactionDetailId() {
        return transactionDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ANALIZE_TRANSACTION.transactionDetailId
     *
     * @param transactionDetailId the value for ANALIZE_TRANSACTION.transactionDetailId
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setTransactionDetailId(Integer transactionDetailId) {
        this.transactionDetailId = transactionDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ANALIZE_TRANSACTION.currentMillis
     *
     * @return the value of ANALIZE_TRANSACTION.currentMillis
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public BigDecimal getCurrentMillis() {
        return currentMillis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ANALIZE_TRANSACTION.currentMillis
     *
     * @param currentMillis the value for ANALIZE_TRANSACTION.currentMillis
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setCurrentMillis(BigDecimal currentMillis) {
        this.currentMillis = currentMillis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ANALIZE_TRANSACTION.status
     *
     * @return the value of ANALIZE_TRANSACTION.status
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ANALIZE_TRANSACTION.status
     *
     * @param status the value for ANALIZE_TRANSACTION.status
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ANALIZE_TRANSACTION.uuid
     *
     * @return the value of ANALIZE_TRANSACTION.uuid
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ANALIZE_TRANSACTION.uuid
     *
     * @param uuid the value for ANALIZE_TRANSACTION.uuid
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ANALIZE_TRANSACTION.httpRefer
     *
     * @return the value of ANALIZE_TRANSACTION.httpRefer
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getHttpRefer() {
        return httpRefer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ANALIZE_TRANSACTION.httpRefer
     *
     * @param httpRefer the value for ANALIZE_TRANSACTION.httpRefer
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setHttpRefer(String httpRefer) {
        this.httpRefer = httpRefer;
    }
}