package com.ticnow.security.model.admin;

public class Aspect {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASPECT.ID_ASPECT
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer ID_ASPECT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASPECT.id_aspect_action
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id_aspect_action;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASPECT.id_risk_level
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id_risk_level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASPECT.ASPECT_NAME
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String ASPECT_NAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASPECT.ASPECT_TYPE
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String ASPECT_TYPE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASPECT.STATE
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String STATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASPECT.ID_ASPECT
     *
     * @return the value of ASPECT.ID_ASPECT
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getID_ASPECT() {
        return ID_ASPECT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASPECT.ID_ASPECT
     *
     * @param ID_ASPECT the value for ASPECT.ID_ASPECT
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setID_ASPECT(Integer ID_ASPECT) {
        this.ID_ASPECT = ID_ASPECT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASPECT.id_aspect_action
     *
     * @return the value of ASPECT.id_aspect_action
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId_aspect_action() {
        return id_aspect_action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASPECT.id_aspect_action
     *
     * @param id_aspect_action the value for ASPECT.id_aspect_action
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId_aspect_action(Integer id_aspect_action) {
        this.id_aspect_action = id_aspect_action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASPECT.id_risk_level
     *
     * @return the value of ASPECT.id_risk_level
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId_risk_level() {
        return id_risk_level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASPECT.id_risk_level
     *
     * @param id_risk_level the value for ASPECT.id_risk_level
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId_risk_level(Integer id_risk_level) {
        this.id_risk_level = id_risk_level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASPECT.ASPECT_NAME
     *
     * @return the value of ASPECT.ASPECT_NAME
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getASPECT_NAME() {
        return ASPECT_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASPECT.ASPECT_NAME
     *
     * @param ASPECT_NAME the value for ASPECT.ASPECT_NAME
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setASPECT_NAME(String ASPECT_NAME) {
        this.ASPECT_NAME = ASPECT_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASPECT.ASPECT_TYPE
     *
     * @return the value of ASPECT.ASPECT_TYPE
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getASPECT_TYPE() {
        return ASPECT_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASPECT.ASPECT_TYPE
     *
     * @param ASPECT_TYPE the value for ASPECT.ASPECT_TYPE
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setASPECT_TYPE(String ASPECT_TYPE) {
        this.ASPECT_TYPE = ASPECT_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASPECT.STATE
     *
     * @return the value of ASPECT.STATE
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getSTATE() {
        return STATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASPECT.STATE
     *
     * @param STATE the value for ASPECT.STATE
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setSTATE(String STATE) {
        this.STATE = STATE;
    }
}