package com.ticnow.security.model.admin;

public class Authenticators {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTHENTICATORS.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTHENTICATORS.authenticator_name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String authenticator_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTHENTICATORS.timeout
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String timeout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTHENTICATORS.backend
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String backend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTHENTICATORS.maxIntent
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String maxIntent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTHENTICATORS.uuid
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTHENTICATORS.onTimeoutAction
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String onTimeoutAction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTHENTICATORS.onErrorAction
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String onErrorAction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTHENTICATORS.maxIntentAction
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String maxIntentAction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTHENTICATORS.institution_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Long institution_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTHENTICATORS.id
     *
     * @return the value of AUTHENTICATORS.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTHENTICATORS.id
     *
     * @param id the value for AUTHENTICATORS.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTHENTICATORS.authenticator_name
     *
     * @return the value of AUTHENTICATORS.authenticator_name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getAuthenticator_name() {
        return authenticator_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTHENTICATORS.authenticator_name
     *
     * @param authenticator_name the value for AUTHENTICATORS.authenticator_name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setAuthenticator_name(String authenticator_name) {
        this.authenticator_name = authenticator_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTHENTICATORS.timeout
     *
     * @return the value of AUTHENTICATORS.timeout
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getTimeout() {
        return timeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTHENTICATORS.timeout
     *
     * @param timeout the value for AUTHENTICATORS.timeout
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setTimeout(String timeout) {
        this.timeout = timeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTHENTICATORS.backend
     *
     * @return the value of AUTHENTICATORS.backend
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getBackend() {
        return backend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTHENTICATORS.backend
     *
     * @param backend the value for AUTHENTICATORS.backend
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setBackend(String backend) {
        this.backend = backend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTHENTICATORS.maxIntent
     *
     * @return the value of AUTHENTICATORS.maxIntent
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getMaxIntent() {
        return maxIntent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTHENTICATORS.maxIntent
     *
     * @param maxIntent the value for AUTHENTICATORS.maxIntent
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setMaxIntent(String maxIntent) {
        this.maxIntent = maxIntent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTHENTICATORS.uuid
     *
     * @return the value of AUTHENTICATORS.uuid
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTHENTICATORS.uuid
     *
     * @param uuid the value for AUTHENTICATORS.uuid
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTHENTICATORS.onTimeoutAction
     *
     * @return the value of AUTHENTICATORS.onTimeoutAction
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getOnTimeoutAction() {
        return onTimeoutAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTHENTICATORS.onTimeoutAction
     *
     * @param onTimeoutAction the value for AUTHENTICATORS.onTimeoutAction
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setOnTimeoutAction(String onTimeoutAction) {
        this.onTimeoutAction = onTimeoutAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTHENTICATORS.onErrorAction
     *
     * @return the value of AUTHENTICATORS.onErrorAction
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getOnErrorAction() {
        return onErrorAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTHENTICATORS.onErrorAction
     *
     * @param onErrorAction the value for AUTHENTICATORS.onErrorAction
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setOnErrorAction(String onErrorAction) {
        this.onErrorAction = onErrorAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTHENTICATORS.maxIntentAction
     *
     * @return the value of AUTHENTICATORS.maxIntentAction
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getMaxIntentAction() {
        return maxIntentAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTHENTICATORS.maxIntentAction
     *
     * @param maxIntentAction the value for AUTHENTICATORS.maxIntentAction
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setMaxIntentAction(String maxIntentAction) {
        this.maxIntentAction = maxIntentAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTHENTICATORS.institution_id
     *
     * @return the value of AUTHENTICATORS.institution_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Long getInstitution_id() {
        return institution_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTHENTICATORS.institution_id
     *
     * @param institution_id the value for AUTHENTICATORS.institution_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setInstitution_id(Long institution_id) {
        this.institution_id = institution_id;
    }
}