package com.ticnow.security.model.admin;

public class BlacklistIp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BLACKLIST_IP.id_blacklist_ip
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id_blacklist_ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BLACKLIST_IP.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BLACKLIST_IP.ip_address
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String ip_address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BLACKLIST_IP.reason
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BLACKLIST_IP.type_blocking
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String type_blocking;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BLACKLIST_IP.blocking_date
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String blocking_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BLACKLIST_IP.state
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLACKLIST_IP.id_blacklist_ip
     *
     * @return the value of BLACKLIST_IP.id_blacklist_ip
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId_blacklist_ip() {
        return id_blacklist_ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLACKLIST_IP.id_blacklist_ip
     *
     * @param id_blacklist_ip the value for BLACKLIST_IP.id_blacklist_ip
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId_blacklist_ip(Integer id_blacklist_ip) {
        this.id_blacklist_ip = id_blacklist_ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLACKLIST_IP.id
     *
     * @return the value of BLACKLIST_IP.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLACKLIST_IP.id
     *
     * @param id the value for BLACKLIST_IP.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLACKLIST_IP.ip_address
     *
     * @return the value of BLACKLIST_IP.ip_address
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getIp_address() {
        return ip_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLACKLIST_IP.ip_address
     *
     * @param ip_address the value for BLACKLIST_IP.ip_address
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setIp_address(String ip_address) {
        this.ip_address = ip_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLACKLIST_IP.reason
     *
     * @return the value of BLACKLIST_IP.reason
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLACKLIST_IP.reason
     *
     * @param reason the value for BLACKLIST_IP.reason
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLACKLIST_IP.type_blocking
     *
     * @return the value of BLACKLIST_IP.type_blocking
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getType_blocking() {
        return type_blocking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLACKLIST_IP.type_blocking
     *
     * @param type_blocking the value for BLACKLIST_IP.type_blocking
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setType_blocking(String type_blocking) {
        this.type_blocking = type_blocking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLACKLIST_IP.blocking_date
     *
     * @return the value of BLACKLIST_IP.blocking_date
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getBlocking_date() {
        return blocking_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLACKLIST_IP.blocking_date
     *
     * @param blocking_date the value for BLACKLIST_IP.blocking_date
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setBlocking_date(String blocking_date) {
        this.blocking_date = blocking_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLACKLIST_IP.state
     *
     * @return the value of BLACKLIST_IP.state
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLACKLIST_IP.state
     *
     * @param state the value for BLACKLIST_IP.state
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setState(String state) {
        this.state = state;
    }
}