package com.ticnow.security.model.admin;

public class BlacklistCountry {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BLACKLIST_COUNTRY.id_blacklist_country
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id_blacklist_country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BLACKLIST_COUNTRY.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BLACKLIST_COUNTRY.country_name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String country_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BLACKLIST_COUNTRY.reason
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BLACKLIST_COUNTRY.type_blocking
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String type_blocking;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BLACKLIST_COUNTRY.blocking_date
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String blocking_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BLACKLIST_COUNTRY.state
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLACKLIST_COUNTRY.id_blacklist_country
     *
     * @return the value of BLACKLIST_COUNTRY.id_blacklist_country
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId_blacklist_country() {
        return id_blacklist_country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLACKLIST_COUNTRY.id_blacklist_country
     *
     * @param id_blacklist_country the value for BLACKLIST_COUNTRY.id_blacklist_country
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId_blacklist_country(Integer id_blacklist_country) {
        this.id_blacklist_country = id_blacklist_country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLACKLIST_COUNTRY.id
     *
     * @return the value of BLACKLIST_COUNTRY.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLACKLIST_COUNTRY.id
     *
     * @param id the value for BLACKLIST_COUNTRY.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLACKLIST_COUNTRY.country_name
     *
     * @return the value of BLACKLIST_COUNTRY.country_name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getCountry_name() {
        return country_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLACKLIST_COUNTRY.country_name
     *
     * @param country_name the value for BLACKLIST_COUNTRY.country_name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setCountry_name(String country_name) {
        this.country_name = country_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLACKLIST_COUNTRY.reason
     *
     * @return the value of BLACKLIST_COUNTRY.reason
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLACKLIST_COUNTRY.reason
     *
     * @param reason the value for BLACKLIST_COUNTRY.reason
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLACKLIST_COUNTRY.type_blocking
     *
     * @return the value of BLACKLIST_COUNTRY.type_blocking
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getType_blocking() {
        return type_blocking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLACKLIST_COUNTRY.type_blocking
     *
     * @param type_blocking the value for BLACKLIST_COUNTRY.type_blocking
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setType_blocking(String type_blocking) {
        this.type_blocking = type_blocking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLACKLIST_COUNTRY.blocking_date
     *
     * @return the value of BLACKLIST_COUNTRY.blocking_date
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getBlocking_date() {
        return blocking_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLACKLIST_COUNTRY.blocking_date
     *
     * @param blocking_date the value for BLACKLIST_COUNTRY.blocking_date
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setBlocking_date(String blocking_date) {
        this.blocking_date = blocking_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BLACKLIST_COUNTRY.state
     *
     * @return the value of BLACKLIST_COUNTRY.state
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BLACKLIST_COUNTRY.state
     *
     * @param state the value for BLACKLIST_COUNTRY.state
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setState(String state) {
        this.state = state;
    }
}