package com.ticnow.security.model.admin;

public class Channel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHANNEL.id_channel
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id_channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHANNEL.id_channel_states
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id_channel_states;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHANNEL.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHANNEL.channel_name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String channel_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHANNEL.channel_code
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String channel_code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHANNEL.id_channel
     *
     * @return the value of CHANNEL.id_channel
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId_channel() {
        return id_channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHANNEL.id_channel
     *
     * @param id_channel the value for CHANNEL.id_channel
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId_channel(Integer id_channel) {
        this.id_channel = id_channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHANNEL.id_channel_states
     *
     * @return the value of CHANNEL.id_channel_states
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId_channel_states() {
        return id_channel_states;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHANNEL.id_channel_states
     *
     * @param id_channel_states the value for CHANNEL.id_channel_states
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId_channel_states(Integer id_channel_states) {
        this.id_channel_states = id_channel_states;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHANNEL.id
     *
     * @return the value of CHANNEL.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHANNEL.id
     *
     * @param id the value for CHANNEL.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHANNEL.channel_name
     *
     * @return the value of CHANNEL.channel_name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getChannel_name() {
        return channel_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHANNEL.channel_name
     *
     * @param channel_name the value for CHANNEL.channel_name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setChannel_name(String channel_name) {
        this.channel_name = channel_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHANNEL.channel_code
     *
     * @return the value of CHANNEL.channel_code
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getChannel_code() {
        return channel_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHANNEL.channel_code
     *
     * @param channel_code the value for CHANNEL.channel_code
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setChannel_code(String channel_code) {
        this.channel_code = channel_code;
    }
}