package com.ticnow.security.model.admin;

public class ChannelStates {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHANNEL_STATES.id_channel_states
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id_channel_states;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHANNEL_STATES.channel_states_name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String channel_states_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHANNEL_STATES.id_channel_states
     *
     * @return the value of CHANNEL_STATES.id_channel_states
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId_channel_states() {
        return id_channel_states;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHANNEL_STATES.id_channel_states
     *
     * @param id_channel_states the value for CHANNEL_STATES.id_channel_states
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId_channel_states(Integer id_channel_states) {
        this.id_channel_states = id_channel_states;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHANNEL_STATES.channel_states_name
     *
     * @return the value of CHANNEL_STATES.channel_states_name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getChannel_states_name() {
        return channel_states_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHANNEL_STATES.channel_states_name
     *
     * @param channel_states_name the value for CHANNEL_STATES.channel_states_name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setChannel_states_name(String channel_states_name) {
        this.channel_states_name = channel_states_name;
    }
}