package com.ticnow.security.model.admin;

import java.util.Date;

public class Device {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.uuid
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.os
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String os;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.device_finger_print
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String device_finger_print;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.telephone_number
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String telephone_number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.status
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.notificationId
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String notificationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.enrollment_date
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Date enrollment_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.institution_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Long institution_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.enrollment_server_key
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String enrollment_server_key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.register_date
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Date register_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.broken
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Boolean broken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.unregister_date
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Date unregister_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.comments
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.os_version
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String os_version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.model
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.enroll_type_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Long enroll_type_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.enabled_auth
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String enabled_auth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.appName
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String appName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.uuid
     *
     * @return the value of DEVICE.uuid
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.uuid
     *
     * @param uuid the value for DEVICE.uuid
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.os
     *
     * @return the value of DEVICE.os
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getOs() {
        return os;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.os
     *
     * @param os the value for DEVICE.os
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setOs(String os) {
        this.os = os;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.device_finger_print
     *
     * @return the value of DEVICE.device_finger_print
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getDevice_finger_print() {
        return device_finger_print;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.device_finger_print
     *
     * @param device_finger_print the value for DEVICE.device_finger_print
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setDevice_finger_print(String device_finger_print) {
        this.device_finger_print = device_finger_print;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.telephone_number
     *
     * @return the value of DEVICE.telephone_number
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getTelephone_number() {
        return telephone_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.telephone_number
     *
     * @param telephone_number the value for DEVICE.telephone_number
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setTelephone_number(String telephone_number) {
        this.telephone_number = telephone_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.status
     *
     * @return the value of DEVICE.status
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.status
     *
     * @param status the value for DEVICE.status
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.notificationId
     *
     * @return the value of DEVICE.notificationId
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getNotificationId() {
        return notificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.notificationId
     *
     * @param notificationId the value for DEVICE.notificationId
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setNotificationId(String notificationId) {
        this.notificationId = notificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.enrollment_date
     *
     * @return the value of DEVICE.enrollment_date
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Date getEnrollment_date() {
        return enrollment_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.enrollment_date
     *
     * @param enrollment_date the value for DEVICE.enrollment_date
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setEnrollment_date(Date enrollment_date) {
        this.enrollment_date = enrollment_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.id
     *
     * @return the value of DEVICE.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.id
     *
     * @param id the value for DEVICE.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.institution_id
     *
     * @return the value of DEVICE.institution_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Long getInstitution_id() {
        return institution_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.institution_id
     *
     * @param institution_id the value for DEVICE.institution_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setInstitution_id(Long institution_id) {
        this.institution_id = institution_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.enrollment_server_key
     *
     * @return the value of DEVICE.enrollment_server_key
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getEnrollment_server_key() {
        return enrollment_server_key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.enrollment_server_key
     *
     * @param enrollment_server_key the value for DEVICE.enrollment_server_key
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setEnrollment_server_key(String enrollment_server_key) {
        this.enrollment_server_key = enrollment_server_key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.register_date
     *
     * @return the value of DEVICE.register_date
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Date getRegister_date() {
        return register_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.register_date
     *
     * @param register_date the value for DEVICE.register_date
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setRegister_date(Date register_date) {
        this.register_date = register_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.broken
     *
     * @return the value of DEVICE.broken
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Boolean getBroken() {
        return broken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.broken
     *
     * @param broken the value for DEVICE.broken
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setBroken(Boolean broken) {
        this.broken = broken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.unregister_date
     *
     * @return the value of DEVICE.unregister_date
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Date getUnregister_date() {
        return unregister_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.unregister_date
     *
     * @param unregister_date the value for DEVICE.unregister_date
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setUnregister_date(Date unregister_date) {
        this.unregister_date = unregister_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.comments
     *
     * @return the value of DEVICE.comments
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.comments
     *
     * @param comments the value for DEVICE.comments
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setComments(String comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.os_version
     *
     * @return the value of DEVICE.os_version
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getOs_version() {
        return os_version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.os_version
     *
     * @param os_version the value for DEVICE.os_version
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setOs_version(String os_version) {
        this.os_version = os_version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.model
     *
     * @return the value of DEVICE.model
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.model
     *
     * @param model the value for DEVICE.model
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.enroll_type_id
     *
     * @return the value of DEVICE.enroll_type_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Long getEnroll_type_id() {
        return enroll_type_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.enroll_type_id
     *
     * @param enroll_type_id the value for DEVICE.enroll_type_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setEnroll_type_id(Long enroll_type_id) {
        this.enroll_type_id = enroll_type_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.enabled_auth
     *
     * @return the value of DEVICE.enabled_auth
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getEnabled_auth() {
        return enabled_auth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.enabled_auth
     *
     * @param enabled_auth the value for DEVICE.enabled_auth
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setEnabled_auth(String enabled_auth) {
        this.enabled_auth = enabled_auth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.appName
     *
     * @return the value of DEVICE.appName
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.appName
     *
     * @param appName the value for DEVICE.appName
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setAppName(String appName) {
        this.appName = appName;
    }
}