package com.ticnow.security.model.admin;

public class EnrollPath {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_PATH.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_PATH.step
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Long step;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_PATH.required
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Boolean required;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_PATH.step_on_fail
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String step_on_fail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_PATH.score
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Long score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_PATH.status
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_PATH.method_enroll_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Long method_enroll_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_PATH.institution_enroll_def_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Long institution_enroll_def_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_PATH.enroll_definition_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Long enroll_definition_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_PATH.next_action
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Long next_action;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_PATH.optional_step
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Long optional_step;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_PATH.ponderateResult
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Boolean ponderateResult;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_PATH.id
     *
     * @return the value of ENROLL_PATH.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_PATH.id
     *
     * @param id the value for ENROLL_PATH.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_PATH.step
     *
     * @return the value of ENROLL_PATH.step
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Long getStep() {
        return step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_PATH.step
     *
     * @param step the value for ENROLL_PATH.step
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setStep(Long step) {
        this.step = step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_PATH.required
     *
     * @return the value of ENROLL_PATH.required
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Boolean getRequired() {
        return required;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_PATH.required
     *
     * @param required the value for ENROLL_PATH.required
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setRequired(Boolean required) {
        this.required = required;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_PATH.step_on_fail
     *
     * @return the value of ENROLL_PATH.step_on_fail
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getStep_on_fail() {
        return step_on_fail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_PATH.step_on_fail
     *
     * @param step_on_fail the value for ENROLL_PATH.step_on_fail
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setStep_on_fail(String step_on_fail) {
        this.step_on_fail = step_on_fail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_PATH.score
     *
     * @return the value of ENROLL_PATH.score
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Long getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_PATH.score
     *
     * @param score the value for ENROLL_PATH.score
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setScore(Long score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_PATH.status
     *
     * @return the value of ENROLL_PATH.status
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_PATH.status
     *
     * @param status the value for ENROLL_PATH.status
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_PATH.method_enroll_id
     *
     * @return the value of ENROLL_PATH.method_enroll_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Long getMethod_enroll_id() {
        return method_enroll_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_PATH.method_enroll_id
     *
     * @param method_enroll_id the value for ENROLL_PATH.method_enroll_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setMethod_enroll_id(Long method_enroll_id) {
        this.method_enroll_id = method_enroll_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_PATH.institution_enroll_def_id
     *
     * @return the value of ENROLL_PATH.institution_enroll_def_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Long getInstitution_enroll_def_id() {
        return institution_enroll_def_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_PATH.institution_enroll_def_id
     *
     * @param institution_enroll_def_id the value for ENROLL_PATH.institution_enroll_def_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setInstitution_enroll_def_id(Long institution_enroll_def_id) {
        this.institution_enroll_def_id = institution_enroll_def_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_PATH.enroll_definition_id
     *
     * @return the value of ENROLL_PATH.enroll_definition_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Long getEnroll_definition_id() {
        return enroll_definition_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_PATH.enroll_definition_id
     *
     * @param enroll_definition_id the value for ENROLL_PATH.enroll_definition_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setEnroll_definition_id(Long enroll_definition_id) {
        this.enroll_definition_id = enroll_definition_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_PATH.next_action
     *
     * @return the value of ENROLL_PATH.next_action
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Long getNext_action() {
        return next_action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_PATH.next_action
     *
     * @param next_action the value for ENROLL_PATH.next_action
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setNext_action(Long next_action) {
        this.next_action = next_action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_PATH.optional_step
     *
     * @return the value of ENROLL_PATH.optional_step
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Long getOptional_step() {
        return optional_step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_PATH.optional_step
     *
     * @param optional_step the value for ENROLL_PATH.optional_step
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setOptional_step(Long optional_step) {
        this.optional_step = optional_step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_PATH.ponderateResult
     *
     * @return the value of ENROLL_PATH.ponderateResult
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Boolean getPonderateResult() {
        return ponderateResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_PATH.ponderateResult
     *
     * @param ponderateResult the value for ENROLL_PATH.ponderateResult
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setPonderateResult(Boolean ponderateResult) {
        this.ponderateResult = ponderateResult;
    }
}