package com.ticnow.security.model.admin;

import java.util.Date;

public class EnrollSmsCodes {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_SMS_CODES.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_SMS_CODES.sms_code
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String sms_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_SMS_CODES.uuid_device
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String uuid_device;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_SMS_CODES.status
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_SMS_CODES.expires_at
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Date expires_at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_SMS_CODES.create_time
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Date create_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_SMS_CODES.id
     *
     * @return the value of ENROLL_SMS_CODES.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_SMS_CODES.id
     *
     * @param id the value for ENROLL_SMS_CODES.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_SMS_CODES.sms_code
     *
     * @return the value of ENROLL_SMS_CODES.sms_code
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getSms_code() {
        return sms_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_SMS_CODES.sms_code
     *
     * @param sms_code the value for ENROLL_SMS_CODES.sms_code
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setSms_code(String sms_code) {
        this.sms_code = sms_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_SMS_CODES.uuid_device
     *
     * @return the value of ENROLL_SMS_CODES.uuid_device
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getUuid_device() {
        return uuid_device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_SMS_CODES.uuid_device
     *
     * @param uuid_device the value for ENROLL_SMS_CODES.uuid_device
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setUuid_device(String uuid_device) {
        this.uuid_device = uuid_device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_SMS_CODES.status
     *
     * @return the value of ENROLL_SMS_CODES.status
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_SMS_CODES.status
     *
     * @param status the value for ENROLL_SMS_CODES.status
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_SMS_CODES.expires_at
     *
     * @return the value of ENROLL_SMS_CODES.expires_at
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Date getExpires_at() {
        return expires_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_SMS_CODES.expires_at
     *
     * @param expires_at the value for ENROLL_SMS_CODES.expires_at
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setExpires_at(Date expires_at) {
        this.expires_at = expires_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_SMS_CODES.create_time
     *
     * @return the value of ENROLL_SMS_CODES.create_time
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_SMS_CODES.create_time
     *
     * @param create_time the value for ENROLL_SMS_CODES.create_time
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }
}