package com.ticnow.security.model.admin;

import java.util.Date;

public class EnrollDocument {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_DOCUMENT.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_DOCUMENT.document_number
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String document_number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_DOCUMENT.document_type
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String document_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_DOCUMENT.document_expired_date
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Date document_expired_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_DOCUMENT.date_of_birth_on_document
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Date date_of_birth_on_document;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_DOCUMENT.names
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String names;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_DOCUMENT.surnames
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String surnames;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_DOCUMENT.optional1
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String optional1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_DOCUMENT.optional2
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String optional2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_DOCUMENT.check_number
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String check_number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_DOCUMENT.check_date_of_birth
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String check_date_of_birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_DOCUMENT.check_expiration_date
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String check_expiration_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_DOCUMENT.check_composite
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String check_composite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_DOCUMENT.valid_number
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Boolean valid_number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_DOCUMENT.valid_date_of_birth
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Boolean valid_date_of_birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_DOCUMENT.valid_expiration_date
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Boolean valid_expiration_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_DOCUMENT.user_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_DOCUMENT.nationality
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer nationality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_DOCUMENT.issuer
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer issuer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_DOCUMENT.valid_score
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String valid_score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_DOCUMENT.type
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_DOCUMENT.mrz_type
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String mrz_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_DOCUMENT.uuid_device
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String uuid_device;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_DOCUMENT.image_document
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private byte[] image_document;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_DOCUMENT.id
     *
     * @return the value of ENROLL_DOCUMENT.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_DOCUMENT.id
     *
     * @param id the value for ENROLL_DOCUMENT.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_DOCUMENT.document_number
     *
     * @return the value of ENROLL_DOCUMENT.document_number
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getDocument_number() {
        return document_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_DOCUMENT.document_number
     *
     * @param document_number the value for ENROLL_DOCUMENT.document_number
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setDocument_number(String document_number) {
        this.document_number = document_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_DOCUMENT.document_type
     *
     * @return the value of ENROLL_DOCUMENT.document_type
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getDocument_type() {
        return document_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_DOCUMENT.document_type
     *
     * @param document_type the value for ENROLL_DOCUMENT.document_type
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setDocument_type(String document_type) {
        this.document_type = document_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_DOCUMENT.document_expired_date
     *
     * @return the value of ENROLL_DOCUMENT.document_expired_date
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Date getDocument_expired_date() {
        return document_expired_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_DOCUMENT.document_expired_date
     *
     * @param document_expired_date the value for ENROLL_DOCUMENT.document_expired_date
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setDocument_expired_date(Date document_expired_date) {
        this.document_expired_date = document_expired_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_DOCUMENT.date_of_birth_on_document
     *
     * @return the value of ENROLL_DOCUMENT.date_of_birth_on_document
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Date getDate_of_birth_on_document() {
        return date_of_birth_on_document;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_DOCUMENT.date_of_birth_on_document
     *
     * @param date_of_birth_on_document the value for ENROLL_DOCUMENT.date_of_birth_on_document
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setDate_of_birth_on_document(Date date_of_birth_on_document) {
        this.date_of_birth_on_document = date_of_birth_on_document;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_DOCUMENT.names
     *
     * @return the value of ENROLL_DOCUMENT.names
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getNames() {
        return names;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_DOCUMENT.names
     *
     * @param names the value for ENROLL_DOCUMENT.names
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setNames(String names) {
        this.names = names;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_DOCUMENT.surnames
     *
     * @return the value of ENROLL_DOCUMENT.surnames
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getSurnames() {
        return surnames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_DOCUMENT.surnames
     *
     * @param surnames the value for ENROLL_DOCUMENT.surnames
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setSurnames(String surnames) {
        this.surnames = surnames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_DOCUMENT.optional1
     *
     * @return the value of ENROLL_DOCUMENT.optional1
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getOptional1() {
        return optional1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_DOCUMENT.optional1
     *
     * @param optional1 the value for ENROLL_DOCUMENT.optional1
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setOptional1(String optional1) {
        this.optional1 = optional1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_DOCUMENT.optional2
     *
     * @return the value of ENROLL_DOCUMENT.optional2
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getOptional2() {
        return optional2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_DOCUMENT.optional2
     *
     * @param optional2 the value for ENROLL_DOCUMENT.optional2
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setOptional2(String optional2) {
        this.optional2 = optional2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_DOCUMENT.check_number
     *
     * @return the value of ENROLL_DOCUMENT.check_number
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getCheck_number() {
        return check_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_DOCUMENT.check_number
     *
     * @param check_number the value for ENROLL_DOCUMENT.check_number
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setCheck_number(String check_number) {
        this.check_number = check_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_DOCUMENT.check_date_of_birth
     *
     * @return the value of ENROLL_DOCUMENT.check_date_of_birth
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getCheck_date_of_birth() {
        return check_date_of_birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_DOCUMENT.check_date_of_birth
     *
     * @param check_date_of_birth the value for ENROLL_DOCUMENT.check_date_of_birth
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setCheck_date_of_birth(String check_date_of_birth) {
        this.check_date_of_birth = check_date_of_birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_DOCUMENT.check_expiration_date
     *
     * @return the value of ENROLL_DOCUMENT.check_expiration_date
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getCheck_expiration_date() {
        return check_expiration_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_DOCUMENT.check_expiration_date
     *
     * @param check_expiration_date the value for ENROLL_DOCUMENT.check_expiration_date
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setCheck_expiration_date(String check_expiration_date) {
        this.check_expiration_date = check_expiration_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_DOCUMENT.check_composite
     *
     * @return the value of ENROLL_DOCUMENT.check_composite
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getCheck_composite() {
        return check_composite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_DOCUMENT.check_composite
     *
     * @param check_composite the value for ENROLL_DOCUMENT.check_composite
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setCheck_composite(String check_composite) {
        this.check_composite = check_composite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_DOCUMENT.valid_number
     *
     * @return the value of ENROLL_DOCUMENT.valid_number
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Boolean getValid_number() {
        return valid_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_DOCUMENT.valid_number
     *
     * @param valid_number the value for ENROLL_DOCUMENT.valid_number
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setValid_number(Boolean valid_number) {
        this.valid_number = valid_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_DOCUMENT.valid_date_of_birth
     *
     * @return the value of ENROLL_DOCUMENT.valid_date_of_birth
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Boolean getValid_date_of_birth() {
        return valid_date_of_birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_DOCUMENT.valid_date_of_birth
     *
     * @param valid_date_of_birth the value for ENROLL_DOCUMENT.valid_date_of_birth
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setValid_date_of_birth(Boolean valid_date_of_birth) {
        this.valid_date_of_birth = valid_date_of_birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_DOCUMENT.valid_expiration_date
     *
     * @return the value of ENROLL_DOCUMENT.valid_expiration_date
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Boolean getValid_expiration_date() {
        return valid_expiration_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_DOCUMENT.valid_expiration_date
     *
     * @param valid_expiration_date the value for ENROLL_DOCUMENT.valid_expiration_date
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setValid_expiration_date(Boolean valid_expiration_date) {
        this.valid_expiration_date = valid_expiration_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_DOCUMENT.user_id
     *
     * @return the value of ENROLL_DOCUMENT.user_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_DOCUMENT.user_id
     *
     * @param user_id the value for ENROLL_DOCUMENT.user_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_DOCUMENT.nationality
     *
     * @return the value of ENROLL_DOCUMENT.nationality
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_DOCUMENT.nationality
     *
     * @param nationality the value for ENROLL_DOCUMENT.nationality
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setNationality(Integer nationality) {
        this.nationality = nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_DOCUMENT.issuer
     *
     * @return the value of ENROLL_DOCUMENT.issuer
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getIssuer() {
        return issuer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_DOCUMENT.issuer
     *
     * @param issuer the value for ENROLL_DOCUMENT.issuer
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setIssuer(Integer issuer) {
        this.issuer = issuer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_DOCUMENT.valid_score
     *
     * @return the value of ENROLL_DOCUMENT.valid_score
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getValid_score() {
        return valid_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_DOCUMENT.valid_score
     *
     * @param valid_score the value for ENROLL_DOCUMENT.valid_score
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setValid_score(String valid_score) {
        this.valid_score = valid_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_DOCUMENT.type
     *
     * @return the value of ENROLL_DOCUMENT.type
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_DOCUMENT.type
     *
     * @param type the value for ENROLL_DOCUMENT.type
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_DOCUMENT.mrz_type
     *
     * @return the value of ENROLL_DOCUMENT.mrz_type
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getMrz_type() {
        return mrz_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_DOCUMENT.mrz_type
     *
     * @param mrz_type the value for ENROLL_DOCUMENT.mrz_type
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setMrz_type(String mrz_type) {
        this.mrz_type = mrz_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_DOCUMENT.uuid_device
     *
     * @return the value of ENROLL_DOCUMENT.uuid_device
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getUuid_device() {
        return uuid_device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_DOCUMENT.uuid_device
     *
     * @param uuid_device the value for ENROLL_DOCUMENT.uuid_device
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setUuid_device(String uuid_device) {
        this.uuid_device = uuid_device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_DOCUMENT.image_document
     *
     * @return the value of ENROLL_DOCUMENT.image_document
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public byte[] getImage_document() {
        return image_document;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_DOCUMENT.image_document
     *
     * @param image_document the value for ENROLL_DOCUMENT.image_document
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setImage_document(byte[] image_document) {
        this.image_document = image_document;
    }
}