package com.ticnow.security.model.admin;

public class EnrollNfcData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_NFC_DATA.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_NFC_DATA.document_code
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String document_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_NFC_DATA.issuing_state
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String issuing_state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_NFC_DATA.primary_identifier
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String primary_identifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_NFC_DATA.secondary_identifier
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String secondary_identifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_NFC_DATA.uuid
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_NFC_DATA.nationality_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer nationality_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_NFC_DATA.document_number
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String document_number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_NFC_DATA.date_of_birth
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String date_of_birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_NFC_DATA.gender
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_NFC_DATA.date_of_expiry
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String date_of_expiry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_NFC_DATA.document_number_check_digit
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String document_number_check_digit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_NFC_DATA.date_of_birth_check_digit
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String date_of_birth_check_digit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_NFC_DATA.date_of_expiry_check_digit
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String date_of_expiry_check_digit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_NFC_DATA.composite_check_digit
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String composite_check_digit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_NFC_DATA.optional_data1
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String optional_data1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_NFC_DATA.optional_data2
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String optional_data2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_NFC_DATA.issue_principal
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String issue_principal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_NFC_DATA.place_of_birth
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String place_of_birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_NFC_DATA.job_name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String job_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_NFC_DATA.uuid_device
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String uuid_device;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_NFC_DATA.user_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer user_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_NFC_DATA.id
     *
     * @return the value of ENROLL_NFC_DATA.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_NFC_DATA.id
     *
     * @param id the value for ENROLL_NFC_DATA.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_NFC_DATA.document_code
     *
     * @return the value of ENROLL_NFC_DATA.document_code
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getDocument_code() {
        return document_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_NFC_DATA.document_code
     *
     * @param document_code the value for ENROLL_NFC_DATA.document_code
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setDocument_code(String document_code) {
        this.document_code = document_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_NFC_DATA.issuing_state
     *
     * @return the value of ENROLL_NFC_DATA.issuing_state
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getIssuing_state() {
        return issuing_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_NFC_DATA.issuing_state
     *
     * @param issuing_state the value for ENROLL_NFC_DATA.issuing_state
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setIssuing_state(String issuing_state) {
        this.issuing_state = issuing_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_NFC_DATA.primary_identifier
     *
     * @return the value of ENROLL_NFC_DATA.primary_identifier
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getPrimary_identifier() {
        return primary_identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_NFC_DATA.primary_identifier
     *
     * @param primary_identifier the value for ENROLL_NFC_DATA.primary_identifier
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setPrimary_identifier(String primary_identifier) {
        this.primary_identifier = primary_identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_NFC_DATA.secondary_identifier
     *
     * @return the value of ENROLL_NFC_DATA.secondary_identifier
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getSecondary_identifier() {
        return secondary_identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_NFC_DATA.secondary_identifier
     *
     * @param secondary_identifier the value for ENROLL_NFC_DATA.secondary_identifier
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setSecondary_identifier(String secondary_identifier) {
        this.secondary_identifier = secondary_identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_NFC_DATA.uuid
     *
     * @return the value of ENROLL_NFC_DATA.uuid
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_NFC_DATA.uuid
     *
     * @param uuid the value for ENROLL_NFC_DATA.uuid
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_NFC_DATA.nationality_id
     *
     * @return the value of ENROLL_NFC_DATA.nationality_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getNationality_id() {
        return nationality_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_NFC_DATA.nationality_id
     *
     * @param nationality_id the value for ENROLL_NFC_DATA.nationality_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setNationality_id(Integer nationality_id) {
        this.nationality_id = nationality_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_NFC_DATA.document_number
     *
     * @return the value of ENROLL_NFC_DATA.document_number
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getDocument_number() {
        return document_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_NFC_DATA.document_number
     *
     * @param document_number the value for ENROLL_NFC_DATA.document_number
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setDocument_number(String document_number) {
        this.document_number = document_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_NFC_DATA.date_of_birth
     *
     * @return the value of ENROLL_NFC_DATA.date_of_birth
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getDate_of_birth() {
        return date_of_birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_NFC_DATA.date_of_birth
     *
     * @param date_of_birth the value for ENROLL_NFC_DATA.date_of_birth
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setDate_of_birth(String date_of_birth) {
        this.date_of_birth = date_of_birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_NFC_DATA.gender
     *
     * @return the value of ENROLL_NFC_DATA.gender
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_NFC_DATA.gender
     *
     * @param gender the value for ENROLL_NFC_DATA.gender
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_NFC_DATA.date_of_expiry
     *
     * @return the value of ENROLL_NFC_DATA.date_of_expiry
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getDate_of_expiry() {
        return date_of_expiry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_NFC_DATA.date_of_expiry
     *
     * @param date_of_expiry the value for ENROLL_NFC_DATA.date_of_expiry
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setDate_of_expiry(String date_of_expiry) {
        this.date_of_expiry = date_of_expiry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_NFC_DATA.document_number_check_digit
     *
     * @return the value of ENROLL_NFC_DATA.document_number_check_digit
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getDocument_number_check_digit() {
        return document_number_check_digit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_NFC_DATA.document_number_check_digit
     *
     * @param document_number_check_digit the value for ENROLL_NFC_DATA.document_number_check_digit
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setDocument_number_check_digit(String document_number_check_digit) {
        this.document_number_check_digit = document_number_check_digit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_NFC_DATA.date_of_birth_check_digit
     *
     * @return the value of ENROLL_NFC_DATA.date_of_birth_check_digit
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getDate_of_birth_check_digit() {
        return date_of_birth_check_digit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_NFC_DATA.date_of_birth_check_digit
     *
     * @param date_of_birth_check_digit the value for ENROLL_NFC_DATA.date_of_birth_check_digit
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setDate_of_birth_check_digit(String date_of_birth_check_digit) {
        this.date_of_birth_check_digit = date_of_birth_check_digit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_NFC_DATA.date_of_expiry_check_digit
     *
     * @return the value of ENROLL_NFC_DATA.date_of_expiry_check_digit
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getDate_of_expiry_check_digit() {
        return date_of_expiry_check_digit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_NFC_DATA.date_of_expiry_check_digit
     *
     * @param date_of_expiry_check_digit the value for ENROLL_NFC_DATA.date_of_expiry_check_digit
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setDate_of_expiry_check_digit(String date_of_expiry_check_digit) {
        this.date_of_expiry_check_digit = date_of_expiry_check_digit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_NFC_DATA.composite_check_digit
     *
     * @return the value of ENROLL_NFC_DATA.composite_check_digit
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getComposite_check_digit() {
        return composite_check_digit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_NFC_DATA.composite_check_digit
     *
     * @param composite_check_digit the value for ENROLL_NFC_DATA.composite_check_digit
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setComposite_check_digit(String composite_check_digit) {
        this.composite_check_digit = composite_check_digit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_NFC_DATA.optional_data1
     *
     * @return the value of ENROLL_NFC_DATA.optional_data1
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getOptional_data1() {
        return optional_data1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_NFC_DATA.optional_data1
     *
     * @param optional_data1 the value for ENROLL_NFC_DATA.optional_data1
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setOptional_data1(String optional_data1) {
        this.optional_data1 = optional_data1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_NFC_DATA.optional_data2
     *
     * @return the value of ENROLL_NFC_DATA.optional_data2
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getOptional_data2() {
        return optional_data2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_NFC_DATA.optional_data2
     *
     * @param optional_data2 the value for ENROLL_NFC_DATA.optional_data2
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setOptional_data2(String optional_data2) {
        this.optional_data2 = optional_data2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_NFC_DATA.issue_principal
     *
     * @return the value of ENROLL_NFC_DATA.issue_principal
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getIssue_principal() {
        return issue_principal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_NFC_DATA.issue_principal
     *
     * @param issue_principal the value for ENROLL_NFC_DATA.issue_principal
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setIssue_principal(String issue_principal) {
        this.issue_principal = issue_principal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_NFC_DATA.place_of_birth
     *
     * @return the value of ENROLL_NFC_DATA.place_of_birth
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getPlace_of_birth() {
        return place_of_birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_NFC_DATA.place_of_birth
     *
     * @param place_of_birth the value for ENROLL_NFC_DATA.place_of_birth
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setPlace_of_birth(String place_of_birth) {
        this.place_of_birth = place_of_birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_NFC_DATA.job_name
     *
     * @return the value of ENROLL_NFC_DATA.job_name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getJob_name() {
        return job_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_NFC_DATA.job_name
     *
     * @param job_name the value for ENROLL_NFC_DATA.job_name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setJob_name(String job_name) {
        this.job_name = job_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_NFC_DATA.uuid_device
     *
     * @return the value of ENROLL_NFC_DATA.uuid_device
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getUuid_device() {
        return uuid_device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_NFC_DATA.uuid_device
     *
     * @param uuid_device the value for ENROLL_NFC_DATA.uuid_device
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setUuid_device(String uuid_device) {
        this.uuid_device = uuid_device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_NFC_DATA.user_id
     *
     * @return the value of ENROLL_NFC_DATA.user_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_NFC_DATA.user_id
     *
     * @param user_id the value for ENROLL_NFC_DATA.user_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }
}