package com.ticnow.security.model.admin;

public class EnrollDiscountsDetails {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_DISCOUNTS_DETAILS.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_DISCOUNTS_DETAILS.uuid
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_DISCOUNTS_DETAILS.finished_enrollment_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer finished_enrollment_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_DISCOUNTS_DETAILS.discount_applied
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Double discount_applied;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_DISCOUNTS_DETAILS.enroll_discounts_type_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer enroll_discounts_type_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL_DISCOUNTS_DETAILS.applied
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Boolean applied;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_DISCOUNTS_DETAILS.id
     *
     * @return the value of ENROLL_DISCOUNTS_DETAILS.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_DISCOUNTS_DETAILS.id
     *
     * @param id the value for ENROLL_DISCOUNTS_DETAILS.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_DISCOUNTS_DETAILS.uuid
     *
     * @return the value of ENROLL_DISCOUNTS_DETAILS.uuid
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_DISCOUNTS_DETAILS.uuid
     *
     * @param uuid the value for ENROLL_DISCOUNTS_DETAILS.uuid
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_DISCOUNTS_DETAILS.finished_enrollment_id
     *
     * @return the value of ENROLL_DISCOUNTS_DETAILS.finished_enrollment_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getFinished_enrollment_id() {
        return finished_enrollment_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_DISCOUNTS_DETAILS.finished_enrollment_id
     *
     * @param finished_enrollment_id the value for ENROLL_DISCOUNTS_DETAILS.finished_enrollment_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setFinished_enrollment_id(Integer finished_enrollment_id) {
        this.finished_enrollment_id = finished_enrollment_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_DISCOUNTS_DETAILS.discount_applied
     *
     * @return the value of ENROLL_DISCOUNTS_DETAILS.discount_applied
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Double getDiscount_applied() {
        return discount_applied;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_DISCOUNTS_DETAILS.discount_applied
     *
     * @param discount_applied the value for ENROLL_DISCOUNTS_DETAILS.discount_applied
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setDiscount_applied(Double discount_applied) {
        this.discount_applied = discount_applied;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_DISCOUNTS_DETAILS.enroll_discounts_type_id
     *
     * @return the value of ENROLL_DISCOUNTS_DETAILS.enroll_discounts_type_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getEnroll_discounts_type_id() {
        return enroll_discounts_type_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_DISCOUNTS_DETAILS.enroll_discounts_type_id
     *
     * @param enroll_discounts_type_id the value for ENROLL_DISCOUNTS_DETAILS.enroll_discounts_type_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setEnroll_discounts_type_id(Integer enroll_discounts_type_id) {
        this.enroll_discounts_type_id = enroll_discounts_type_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL_DISCOUNTS_DETAILS.applied
     *
     * @return the value of ENROLL_DISCOUNTS_DETAILS.applied
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Boolean getApplied() {
        return applied;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL_DISCOUNTS_DETAILS.applied
     *
     * @param applied the value for ENROLL_DISCOUNTS_DETAILS.applied
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setApplied(Boolean applied) {
        this.applied = applied;
    }
}