package com.ticnow.security.model.admin;

public class EnrollDiscountsType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL__DISCOUNTS_TYPE.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL__DISCOUNTS_TYPE.institution_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Long institution_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL__DISCOUNTS_TYPE.name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL__DISCOUNTS_TYPE.discount_type
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String discount_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL__DISCOUNTS_TYPE.discount_to_apply
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Double discount_to_apply;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENROLL__DISCOUNTS_TYPE.status
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL__DISCOUNTS_TYPE.id
     *
     * @return the value of ENROLL__DISCOUNTS_TYPE.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL__DISCOUNTS_TYPE.id
     *
     * @param id the value for ENROLL__DISCOUNTS_TYPE.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL__DISCOUNTS_TYPE.institution_id
     *
     * @return the value of ENROLL__DISCOUNTS_TYPE.institution_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Long getInstitution_id() {
        return institution_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL__DISCOUNTS_TYPE.institution_id
     *
     * @param institution_id the value for ENROLL__DISCOUNTS_TYPE.institution_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setInstitution_id(Long institution_id) {
        this.institution_id = institution_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL__DISCOUNTS_TYPE.name
     *
     * @return the value of ENROLL__DISCOUNTS_TYPE.name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL__DISCOUNTS_TYPE.name
     *
     * @param name the value for ENROLL__DISCOUNTS_TYPE.name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL__DISCOUNTS_TYPE.discount_type
     *
     * @return the value of ENROLL__DISCOUNTS_TYPE.discount_type
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getDiscount_type() {
        return discount_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL__DISCOUNTS_TYPE.discount_type
     *
     * @param discount_type the value for ENROLL__DISCOUNTS_TYPE.discount_type
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setDiscount_type(String discount_type) {
        this.discount_type = discount_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL__DISCOUNTS_TYPE.discount_to_apply
     *
     * @return the value of ENROLL__DISCOUNTS_TYPE.discount_to_apply
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Double getDiscount_to_apply() {
        return discount_to_apply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL__DISCOUNTS_TYPE.discount_to_apply
     *
     * @param discount_to_apply the value for ENROLL__DISCOUNTS_TYPE.discount_to_apply
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setDiscount_to_apply(Double discount_to_apply) {
        this.discount_to_apply = discount_to_apply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENROLL__DISCOUNTS_TYPE.status
     *
     * @return the value of ENROLL__DISCOUNTS_TYPE.status
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENROLL__DISCOUNTS_TYPE.status
     *
     * @param status the value for ENROLL__DISCOUNTS_TYPE.status
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }
}