package com.ticnow.security.model.admin;

import java.math.BigDecimal;

public class ExternalEnrollValidations {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXTERNAL_ENROLL_VALIDATIONS.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXTERNAL_ENROLL_VALIDATIONS.validation_type
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String validation_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXTERNAL_ENROLL_VALIDATIONS.validation_source
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String validation_source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXTERNAL_ENROLL_VALIDATIONS.validation_result
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String validation_result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXTERNAL_ENROLL_VALIDATIONS.enroll_path_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Long enroll_path_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXTERNAL_ENROLL_VALIDATIONS.valid
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Boolean valid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXTERNAL_ENROLL_VALIDATIONS.uuid_device
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String uuid_device;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXTERNAL_ENROLL_VALIDATIONS.aditional_score
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private BigDecimal aditional_score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXTERNAL_ENROLL_VALIDATIONS.id
     *
     * @return the value of EXTERNAL_ENROLL_VALIDATIONS.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXTERNAL_ENROLL_VALIDATIONS.id
     *
     * @param id the value for EXTERNAL_ENROLL_VALIDATIONS.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXTERNAL_ENROLL_VALIDATIONS.validation_type
     *
     * @return the value of EXTERNAL_ENROLL_VALIDATIONS.validation_type
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getValidation_type() {
        return validation_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXTERNAL_ENROLL_VALIDATIONS.validation_type
     *
     * @param validation_type the value for EXTERNAL_ENROLL_VALIDATIONS.validation_type
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setValidation_type(String validation_type) {
        this.validation_type = validation_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXTERNAL_ENROLL_VALIDATIONS.validation_source
     *
     * @return the value of EXTERNAL_ENROLL_VALIDATIONS.validation_source
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getValidation_source() {
        return validation_source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXTERNAL_ENROLL_VALIDATIONS.validation_source
     *
     * @param validation_source the value for EXTERNAL_ENROLL_VALIDATIONS.validation_source
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setValidation_source(String validation_source) {
        this.validation_source = validation_source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXTERNAL_ENROLL_VALIDATIONS.validation_result
     *
     * @return the value of EXTERNAL_ENROLL_VALIDATIONS.validation_result
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getValidation_result() {
        return validation_result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXTERNAL_ENROLL_VALIDATIONS.validation_result
     *
     * @param validation_result the value for EXTERNAL_ENROLL_VALIDATIONS.validation_result
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setValidation_result(String validation_result) {
        this.validation_result = validation_result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXTERNAL_ENROLL_VALIDATIONS.enroll_path_id
     *
     * @return the value of EXTERNAL_ENROLL_VALIDATIONS.enroll_path_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Long getEnroll_path_id() {
        return enroll_path_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXTERNAL_ENROLL_VALIDATIONS.enroll_path_id
     *
     * @param enroll_path_id the value for EXTERNAL_ENROLL_VALIDATIONS.enroll_path_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setEnroll_path_id(Long enroll_path_id) {
        this.enroll_path_id = enroll_path_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXTERNAL_ENROLL_VALIDATIONS.valid
     *
     * @return the value of EXTERNAL_ENROLL_VALIDATIONS.valid
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Boolean getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXTERNAL_ENROLL_VALIDATIONS.valid
     *
     * @param valid the value for EXTERNAL_ENROLL_VALIDATIONS.valid
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setValid(Boolean valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXTERNAL_ENROLL_VALIDATIONS.uuid_device
     *
     * @return the value of EXTERNAL_ENROLL_VALIDATIONS.uuid_device
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getUuid_device() {
        return uuid_device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXTERNAL_ENROLL_VALIDATIONS.uuid_device
     *
     * @param uuid_device the value for EXTERNAL_ENROLL_VALIDATIONS.uuid_device
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setUuid_device(String uuid_device) {
        this.uuid_device = uuid_device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXTERNAL_ENROLL_VALIDATIONS.aditional_score
     *
     * @return the value of EXTERNAL_ENROLL_VALIDATIONS.aditional_score
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public BigDecimal getAditional_score() {
        return aditional_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXTERNAL_ENROLL_VALIDATIONS.aditional_score
     *
     * @param aditional_score the value for EXTERNAL_ENROLL_VALIDATIONS.aditional_score
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setAditional_score(BigDecimal aditional_score) {
        this.aditional_score = aditional_score;
    }
}