package com.ticnow.security.model.admin;

public class InstitutionEnrollDefinition {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION_ENROLL_DEFINITION.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION_ENROLL_DEFINITION.status
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION_ENROLL_DEFINITION.institution_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Long institution_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION_ENROLL_DEFINITION.id
     *
     * @return the value of INSTITUTION_ENROLL_DEFINITION.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION_ENROLL_DEFINITION.id
     *
     * @param id the value for INSTITUTION_ENROLL_DEFINITION.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION_ENROLL_DEFINITION.status
     *
     * @return the value of INSTITUTION_ENROLL_DEFINITION.status
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION_ENROLL_DEFINITION.status
     *
     * @param status the value for INSTITUTION_ENROLL_DEFINITION.status
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION_ENROLL_DEFINITION.institution_id
     *
     * @return the value of INSTITUTION_ENROLL_DEFINITION.institution_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Long getInstitution_id() {
        return institution_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION_ENROLL_DEFINITION.institution_id
     *
     * @param institution_id the value for INSTITUTION_ENROLL_DEFINITION.institution_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setInstitution_id(Long institution_id) {
        this.institution_id = institution_id;
    }
}