package com.ticnow.security.model.admin;

public class InstitutionExternalChallenges {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION_EXTERNAL_CHALLENGES.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION_EXTERNAL_CHALLENGES.institution_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Long institution_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION_EXTERNAL_CHALLENGES.uuid
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION_EXTERNAL_CHALLENGES.challenge_type
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String challenge_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION_EXTERNAL_CHALLENGES.challenge_question
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String challenge_question;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION_EXTERNAL_CHALLENGES.user_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer user_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION_EXTERNAL_CHALLENGES.id
     *
     * @return the value of INSTITUTION_EXTERNAL_CHALLENGES.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION_EXTERNAL_CHALLENGES.id
     *
     * @param id the value for INSTITUTION_EXTERNAL_CHALLENGES.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION_EXTERNAL_CHALLENGES.institution_id
     *
     * @return the value of INSTITUTION_EXTERNAL_CHALLENGES.institution_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Long getInstitution_id() {
        return institution_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION_EXTERNAL_CHALLENGES.institution_id
     *
     * @param institution_id the value for INSTITUTION_EXTERNAL_CHALLENGES.institution_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setInstitution_id(Long institution_id) {
        this.institution_id = institution_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION_EXTERNAL_CHALLENGES.uuid
     *
     * @return the value of INSTITUTION_EXTERNAL_CHALLENGES.uuid
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION_EXTERNAL_CHALLENGES.uuid
     *
     * @param uuid the value for INSTITUTION_EXTERNAL_CHALLENGES.uuid
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION_EXTERNAL_CHALLENGES.challenge_type
     *
     * @return the value of INSTITUTION_EXTERNAL_CHALLENGES.challenge_type
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getChallenge_type() {
        return challenge_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION_EXTERNAL_CHALLENGES.challenge_type
     *
     * @param challenge_type the value for INSTITUTION_EXTERNAL_CHALLENGES.challenge_type
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setChallenge_type(String challenge_type) {
        this.challenge_type = challenge_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION_EXTERNAL_CHALLENGES.challenge_question
     *
     * @return the value of INSTITUTION_EXTERNAL_CHALLENGES.challenge_question
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getChallenge_question() {
        return challenge_question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION_EXTERNAL_CHALLENGES.challenge_question
     *
     * @param challenge_question the value for INSTITUTION_EXTERNAL_CHALLENGES.challenge_question
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setChallenge_question(String challenge_question) {
        this.challenge_question = challenge_question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION_EXTERNAL_CHALLENGES.user_id
     *
     * @return the value of INSTITUTION_EXTERNAL_CHALLENGES.user_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION_EXTERNAL_CHALLENGES.user_id
     *
     * @param user_id the value for INSTITUTION_EXTERNAL_CHALLENGES.user_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }
}