package com.ticnow.security.model.admin;

public class InstitutionSegments {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION_SEGMENTS.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION_SEGMENTS.segment_name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String segment_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION_SEGMENTS.minimal_enroll_scoring
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Double minimal_enroll_scoring;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION_SEGMENTS.minimal_transaction_scoring
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Double minimal_transaction_scoring;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION_SEGMENTS.institution_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Long institution_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION_SEGMENTS.segment_code
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String segment_code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION_SEGMENTS.id
     *
     * @return the value of INSTITUTION_SEGMENTS.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION_SEGMENTS.id
     *
     * @param id the value for INSTITUTION_SEGMENTS.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION_SEGMENTS.segment_name
     *
     * @return the value of INSTITUTION_SEGMENTS.segment_name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getSegment_name() {
        return segment_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION_SEGMENTS.segment_name
     *
     * @param segment_name the value for INSTITUTION_SEGMENTS.segment_name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setSegment_name(String segment_name) {
        this.segment_name = segment_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION_SEGMENTS.minimal_enroll_scoring
     *
     * @return the value of INSTITUTION_SEGMENTS.minimal_enroll_scoring
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Double getMinimal_enroll_scoring() {
        return minimal_enroll_scoring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION_SEGMENTS.minimal_enroll_scoring
     *
     * @param minimal_enroll_scoring the value for INSTITUTION_SEGMENTS.minimal_enroll_scoring
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setMinimal_enroll_scoring(Double minimal_enroll_scoring) {
        this.minimal_enroll_scoring = minimal_enroll_scoring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION_SEGMENTS.minimal_transaction_scoring
     *
     * @return the value of INSTITUTION_SEGMENTS.minimal_transaction_scoring
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Double getMinimal_transaction_scoring() {
        return minimal_transaction_scoring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION_SEGMENTS.minimal_transaction_scoring
     *
     * @param minimal_transaction_scoring the value for INSTITUTION_SEGMENTS.minimal_transaction_scoring
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setMinimal_transaction_scoring(Double minimal_transaction_scoring) {
        this.minimal_transaction_scoring = minimal_transaction_scoring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION_SEGMENTS.institution_id
     *
     * @return the value of INSTITUTION_SEGMENTS.institution_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Long getInstitution_id() {
        return institution_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION_SEGMENTS.institution_id
     *
     * @param institution_id the value for INSTITUTION_SEGMENTS.institution_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setInstitution_id(Long institution_id) {
        this.institution_id = institution_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION_SEGMENTS.segment_code
     *
     * @return the value of INSTITUTION_SEGMENTS.segment_code
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getSegment_code() {
        return segment_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION_SEGMENTS.segment_code
     *
     * @param segment_code the value for INSTITUTION_SEGMENTS.segment_code
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setSegment_code(String segment_code) {
        this.segment_code = segment_code;
    }
}