package com.ticnow.security.model.admin;

public class Institution {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION.name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION.api_user
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String api_user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION.api_key
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String api_key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION.status
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION.minimal_enroll_scoring
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Double minimal_enroll_scoring;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION.minimal_transaction_scoring
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Double minimal_transaction_scoring;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION.apply_device_discounts
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Boolean apply_device_discounts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION.person_group_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String person_group_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION.confidence
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Double confidence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION.ldap_url
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String ldap_url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION.ldap_base
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String ldap_base;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION.smtp_url
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String smtp_url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION.smtp_user
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String smtp_user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION.smtp_password
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String smtp_password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION.timeout_enroll
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String timeout_enroll;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION.timeout_auth
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String timeout_auth;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION.id
     *
     * @return the value of INSTITUTION.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION.id
     *
     * @param id the value for INSTITUTION.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION.name
     *
     * @return the value of INSTITUTION.name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION.name
     *
     * @param name the value for INSTITUTION.name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION.api_user
     *
     * @return the value of INSTITUTION.api_user
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getApi_user() {
        return api_user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION.api_user
     *
     * @param api_user the value for INSTITUTION.api_user
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setApi_user(String api_user) {
        this.api_user = api_user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION.api_key
     *
     * @return the value of INSTITUTION.api_key
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getApi_key() {
        return api_key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION.api_key
     *
     * @param api_key the value for INSTITUTION.api_key
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setApi_key(String api_key) {
        this.api_key = api_key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION.status
     *
     * @return the value of INSTITUTION.status
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION.status
     *
     * @param status the value for INSTITUTION.status
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION.minimal_enroll_scoring
     *
     * @return the value of INSTITUTION.minimal_enroll_scoring
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Double getMinimal_enroll_scoring() {
        return minimal_enroll_scoring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION.minimal_enroll_scoring
     *
     * @param minimal_enroll_scoring the value for INSTITUTION.minimal_enroll_scoring
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setMinimal_enroll_scoring(Double minimal_enroll_scoring) {
        this.minimal_enroll_scoring = minimal_enroll_scoring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION.minimal_transaction_scoring
     *
     * @return the value of INSTITUTION.minimal_transaction_scoring
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Double getMinimal_transaction_scoring() {
        return minimal_transaction_scoring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION.minimal_transaction_scoring
     *
     * @param minimal_transaction_scoring the value for INSTITUTION.minimal_transaction_scoring
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setMinimal_transaction_scoring(Double minimal_transaction_scoring) {
        this.minimal_transaction_scoring = minimal_transaction_scoring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION.apply_device_discounts
     *
     * @return the value of INSTITUTION.apply_device_discounts
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Boolean getApply_device_discounts() {
        return apply_device_discounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION.apply_device_discounts
     *
     * @param apply_device_discounts the value for INSTITUTION.apply_device_discounts
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setApply_device_discounts(Boolean apply_device_discounts) {
        this.apply_device_discounts = apply_device_discounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION.person_group_id
     *
     * @return the value of INSTITUTION.person_group_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getPerson_group_id() {
        return person_group_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION.person_group_id
     *
     * @param person_group_id the value for INSTITUTION.person_group_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setPerson_group_id(String person_group_id) {
        this.person_group_id = person_group_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION.confidence
     *
     * @return the value of INSTITUTION.confidence
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Double getConfidence() {
        return confidence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION.confidence
     *
     * @param confidence the value for INSTITUTION.confidence
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setConfidence(Double confidence) {
        this.confidence = confidence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION.ldap_url
     *
     * @return the value of INSTITUTION.ldap_url
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getLdap_url() {
        return ldap_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION.ldap_url
     *
     * @param ldap_url the value for INSTITUTION.ldap_url
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setLdap_url(String ldap_url) {
        this.ldap_url = ldap_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION.ldap_base
     *
     * @return the value of INSTITUTION.ldap_base
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getLdap_base() {
        return ldap_base;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION.ldap_base
     *
     * @param ldap_base the value for INSTITUTION.ldap_base
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setLdap_base(String ldap_base) {
        this.ldap_base = ldap_base;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION.smtp_url
     *
     * @return the value of INSTITUTION.smtp_url
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getSmtp_url() {
        return smtp_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION.smtp_url
     *
     * @param smtp_url the value for INSTITUTION.smtp_url
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setSmtp_url(String smtp_url) {
        this.smtp_url = smtp_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION.smtp_user
     *
     * @return the value of INSTITUTION.smtp_user
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getSmtp_user() {
        return smtp_user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION.smtp_user
     *
     * @param smtp_user the value for INSTITUTION.smtp_user
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setSmtp_user(String smtp_user) {
        this.smtp_user = smtp_user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION.smtp_password
     *
     * @return the value of INSTITUTION.smtp_password
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getSmtp_password() {
        return smtp_password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION.smtp_password
     *
     * @param smtp_password the value for INSTITUTION.smtp_password
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setSmtp_password(String smtp_password) {
        this.smtp_password = smtp_password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION.timeout_enroll
     *
     * @return the value of INSTITUTION.timeout_enroll
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getTimeout_enroll() {
        return timeout_enroll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION.timeout_enroll
     *
     * @param timeout_enroll the value for INSTITUTION.timeout_enroll
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setTimeout_enroll(String timeout_enroll) {
        this.timeout_enroll = timeout_enroll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION.timeout_auth
     *
     * @return the value of INSTITUTION.timeout_auth
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getTimeout_auth() {
        return timeout_auth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION.timeout_auth
     *
     * @param timeout_auth the value for INSTITUTION.timeout_auth
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setTimeout_auth(String timeout_auth) {
        this.timeout_auth = timeout_auth;
    }
}