package com.ticnow.security.model.admin;

public class InstitutionAuthenticators {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION_AUTHENTICATORS.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION_AUTHENTICATORS.authenticators_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer authenticators_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION_AUTHENTICATORS.institution_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Long institution_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION_AUTHENTICATORS.id
     *
     * @return the value of INSTITUTION_AUTHENTICATORS.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION_AUTHENTICATORS.id
     *
     * @param id the value for INSTITUTION_AUTHENTICATORS.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION_AUTHENTICATORS.authenticators_id
     *
     * @return the value of INSTITUTION_AUTHENTICATORS.authenticators_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getAuthenticators_id() {
        return authenticators_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION_AUTHENTICATORS.authenticators_id
     *
     * @param authenticators_id the value for INSTITUTION_AUTHENTICATORS.authenticators_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setAuthenticators_id(Integer authenticators_id) {
        this.authenticators_id = authenticators_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION_AUTHENTICATORS.institution_id
     *
     * @return the value of INSTITUTION_AUTHENTICATORS.institution_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Long getInstitution_id() {
        return institution_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION_AUTHENTICATORS.institution_id
     *
     * @param institution_id the value for INSTITUTION_AUTHENTICATORS.institution_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setInstitution_id(Long institution_id) {
        this.institution_id = institution_id;
    }
}