package com.ticnow.security.model.admin;

public class InstitutionTransaction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION_TRANSACTION.id_institution_transaction
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Long id_institution_transaction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION_TRANSACTION.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION_TRANSACTION.name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION_TRANSACTION.description
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION_TRANSACTION.uuid
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION_TRANSACTION.state
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Short state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION_TRANSACTION.id_institution_transaction
     *
     * @return the value of INSTITUTION_TRANSACTION.id_institution_transaction
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Long getId_institution_transaction() {
        return id_institution_transaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION_TRANSACTION.id_institution_transaction
     *
     * @param id_institution_transaction the value for INSTITUTION_TRANSACTION.id_institution_transaction
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId_institution_transaction(Long id_institution_transaction) {
        this.id_institution_transaction = id_institution_transaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION_TRANSACTION.id
     *
     * @return the value of INSTITUTION_TRANSACTION.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION_TRANSACTION.id
     *
     * @param id the value for INSTITUTION_TRANSACTION.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION_TRANSACTION.name
     *
     * @return the value of INSTITUTION_TRANSACTION.name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION_TRANSACTION.name
     *
     * @param name the value for INSTITUTION_TRANSACTION.name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION_TRANSACTION.description
     *
     * @return the value of INSTITUTION_TRANSACTION.description
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION_TRANSACTION.description
     *
     * @param description the value for INSTITUTION_TRANSACTION.description
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION_TRANSACTION.uuid
     *
     * @return the value of INSTITUTION_TRANSACTION.uuid
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION_TRANSACTION.uuid
     *
     * @param uuid the value for INSTITUTION_TRANSACTION.uuid
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION_TRANSACTION.state
     *
     * @return the value of INSTITUTION_TRANSACTION.state
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION_TRANSACTION.state
     *
     * @param state the value for INSTITUTION_TRANSACTION.state
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setState(Short state) {
        this.state = state;
    }
}