package com.ticnow.security.model.admin;

import java.util.Date;

public class LoginUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGIN_USER.id_login_user
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id_login_user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGIN_USER.id_profile_user
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id_profile_user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGIN_USER.user_identifier
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String user_identifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGIN_USER.email
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGIN_USER.password
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGIN_USER.id_status
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGIN_USER.dateCreation
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Date dateCreation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGIN_USER.institution_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Long institution_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGIN_USER.external
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Boolean external;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGIN_USER.baseLdap
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String baseLdap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGIN_USER.realName
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String realName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGIN_USER.id_login_user
     *
     * @return the value of LOGIN_USER.id_login_user
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId_login_user() {
        return id_login_user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGIN_USER.id_login_user
     *
     * @param id_login_user the value for LOGIN_USER.id_login_user
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId_login_user(Integer id_login_user) {
        this.id_login_user = id_login_user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGIN_USER.id_profile_user
     *
     * @return the value of LOGIN_USER.id_profile_user
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId_profile_user() {
        return id_profile_user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGIN_USER.id_profile_user
     *
     * @param id_profile_user the value for LOGIN_USER.id_profile_user
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId_profile_user(Integer id_profile_user) {
        this.id_profile_user = id_profile_user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGIN_USER.user_identifier
     *
     * @return the value of LOGIN_USER.user_identifier
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getUser_identifier() {
        return user_identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGIN_USER.user_identifier
     *
     * @param user_identifier the value for LOGIN_USER.user_identifier
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setUser_identifier(String user_identifier) {
        this.user_identifier = user_identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGIN_USER.email
     *
     * @return the value of LOGIN_USER.email
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGIN_USER.email
     *
     * @param email the value for LOGIN_USER.email
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGIN_USER.password
     *
     * @return the value of LOGIN_USER.password
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGIN_USER.password
     *
     * @param password the value for LOGIN_USER.password
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGIN_USER.id_status
     *
     * @return the value of LOGIN_USER.id_status
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId_status() {
        return id_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGIN_USER.id_status
     *
     * @param id_status the value for LOGIN_USER.id_status
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId_status(Integer id_status) {
        this.id_status = id_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGIN_USER.dateCreation
     *
     * @return the value of LOGIN_USER.dateCreation
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Date getDateCreation() {
        return dateCreation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGIN_USER.dateCreation
     *
     * @param dateCreation the value for LOGIN_USER.dateCreation
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setDateCreation(Date dateCreation) {
        this.dateCreation = dateCreation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGIN_USER.institution_id
     *
     * @return the value of LOGIN_USER.institution_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Long getInstitution_id() {
        return institution_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGIN_USER.institution_id
     *
     * @param institution_id the value for LOGIN_USER.institution_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setInstitution_id(Long institution_id) {
        this.institution_id = institution_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGIN_USER.external
     *
     * @return the value of LOGIN_USER.external
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Boolean getExternal() {
        return external;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGIN_USER.external
     *
     * @param external the value for LOGIN_USER.external
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setExternal(Boolean external) {
        this.external = external;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGIN_USER.baseLdap
     *
     * @return the value of LOGIN_USER.baseLdap
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getBaseLdap() {
        return baseLdap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGIN_USER.baseLdap
     *
     * @param baseLdap the value for LOGIN_USER.baseLdap
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setBaseLdap(String baseLdap) {
        this.baseLdap = baseLdap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGIN_USER.realName
     *
     * @return the value of LOGIN_USER.realName
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGIN_USER.realName
     *
     * @param realName the value for LOGIN_USER.realName
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }
}