package com.ticnow.security.model.admin;

import java.util.Date;

public class Messages {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MESSAGES.id_menssage
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id_menssage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MESSAGES.id_type_message
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id_type_message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MESSAGES.uuid
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MESSAGES.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MESSAGES.message_title
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String message_title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MESSAGES.description
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MESSAGES.send_date
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Date send_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MESSAGES.receipt_date
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Date receipt_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MESSAGES.state
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MESSAGES.id_menssage
     *
     * @return the value of MESSAGES.id_menssage
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId_menssage() {
        return id_menssage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MESSAGES.id_menssage
     *
     * @param id_menssage the value for MESSAGES.id_menssage
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId_menssage(Integer id_menssage) {
        this.id_menssage = id_menssage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MESSAGES.id_type_message
     *
     * @return the value of MESSAGES.id_type_message
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId_type_message() {
        return id_type_message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MESSAGES.id_type_message
     *
     * @param id_type_message the value for MESSAGES.id_type_message
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId_type_message(Integer id_type_message) {
        this.id_type_message = id_type_message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MESSAGES.uuid
     *
     * @return the value of MESSAGES.uuid
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MESSAGES.uuid
     *
     * @param uuid the value for MESSAGES.uuid
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MESSAGES.id
     *
     * @return the value of MESSAGES.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MESSAGES.id
     *
     * @param id the value for MESSAGES.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MESSAGES.message_title
     *
     * @return the value of MESSAGES.message_title
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getMessage_title() {
        return message_title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MESSAGES.message_title
     *
     * @param message_title the value for MESSAGES.message_title
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setMessage_title(String message_title) {
        this.message_title = message_title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MESSAGES.description
     *
     * @return the value of MESSAGES.description
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MESSAGES.description
     *
     * @param description the value for MESSAGES.description
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MESSAGES.send_date
     *
     * @return the value of MESSAGES.send_date
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Date getSend_date() {
        return send_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MESSAGES.send_date
     *
     * @param send_date the value for MESSAGES.send_date
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setSend_date(Date send_date) {
        this.send_date = send_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MESSAGES.receipt_date
     *
     * @return the value of MESSAGES.receipt_date
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Date getReceipt_date() {
        return receipt_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MESSAGES.receipt_date
     *
     * @param receipt_date the value for MESSAGES.receipt_date
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setReceipt_date(Date receipt_date) {
        this.receipt_date = receipt_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MESSAGES.state
     *
     * @return the value of MESSAGES.state
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MESSAGES.state
     *
     * @param state the value for MESSAGES.state
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setState(String state) {
        this.state = state;
    }
}