package com.ticnow.security.model.admin;

public class Modules {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MODULES.id_modules
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id_modules;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MODULES.module_name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String module_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MODULES.module_code
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String module_code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MODULES.id_modules
     *
     * @return the value of MODULES.id_modules
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId_modules() {
        return id_modules;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MODULES.id_modules
     *
     * @param id_modules the value for MODULES.id_modules
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId_modules(Integer id_modules) {
        this.id_modules = id_modules;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MODULES.module_name
     *
     * @return the value of MODULES.module_name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getModule_name() {
        return module_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MODULES.module_name
     *
     * @param module_name the value for MODULES.module_name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setModule_name(String module_name) {
        this.module_name = module_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MODULES.module_code
     *
     * @return the value of MODULES.module_code
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getModule_code() {
        return module_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MODULES.module_code
     *
     * @param module_code the value for MODULES.module_code
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setModule_code(String module_code) {
        this.module_code = module_code;
    }
}