package com.ticnow.security.model.admin;

public class ModulesActions {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MODULES_ACTIONS.id_module_action
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id_module_action;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MODULES_ACTIONS.id_actions
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id_actions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MODULES_ACTIONS.id_modules
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id_modules;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MODULES_ACTIONS.id_module_action
     *
     * @return the value of MODULES_ACTIONS.id_module_action
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId_module_action() {
        return id_module_action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MODULES_ACTIONS.id_module_action
     *
     * @param id_module_action the value for MODULES_ACTIONS.id_module_action
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId_module_action(Integer id_module_action) {
        this.id_module_action = id_module_action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MODULES_ACTIONS.id_actions
     *
     * @return the value of MODULES_ACTIONS.id_actions
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId_actions() {
        return id_actions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MODULES_ACTIONS.id_actions
     *
     * @param id_actions the value for MODULES_ACTIONS.id_actions
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId_actions(Integer id_actions) {
        this.id_actions = id_actions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MODULES_ACTIONS.id_modules
     *
     * @return the value of MODULES_ACTIONS.id_modules
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId_modules() {
        return id_modules;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MODULES_ACTIONS.id_modules
     *
     * @param id_modules the value for MODULES_ACTIONS.id_modules
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId_modules(Integer id_modules) {
        this.id_modules = id_modules;
    }
}