package com.ticnow.security.model.admin;

import java.util.Date;

public class OtpSmsCodes {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OTP_SMS_CODES.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OTP_SMS_CODES.otpCode
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String otpCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OTP_SMS_CODES.uuidTransaction
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String uuidTransaction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OTP_SMS_CODES.createTime
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OTP_SMS_CODES.expiresAt
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Date expiresAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OTP_SMS_CODES.status
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OTP_SMS_CODES.id
     *
     * @return the value of OTP_SMS_CODES.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OTP_SMS_CODES.id
     *
     * @param id the value for OTP_SMS_CODES.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OTP_SMS_CODES.otpCode
     *
     * @return the value of OTP_SMS_CODES.otpCode
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getOtpCode() {
        return otpCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OTP_SMS_CODES.otpCode
     *
     * @param otpCode the value for OTP_SMS_CODES.otpCode
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setOtpCode(String otpCode) {
        this.otpCode = otpCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OTP_SMS_CODES.uuidTransaction
     *
     * @return the value of OTP_SMS_CODES.uuidTransaction
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getUuidTransaction() {
        return uuidTransaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OTP_SMS_CODES.uuidTransaction
     *
     * @param uuidTransaction the value for OTP_SMS_CODES.uuidTransaction
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setUuidTransaction(String uuidTransaction) {
        this.uuidTransaction = uuidTransaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OTP_SMS_CODES.createTime
     *
     * @return the value of OTP_SMS_CODES.createTime
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OTP_SMS_CODES.createTime
     *
     * @param createTime the value for OTP_SMS_CODES.createTime
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OTP_SMS_CODES.expiresAt
     *
     * @return the value of OTP_SMS_CODES.expiresAt
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Date getExpiresAt() {
        return expiresAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OTP_SMS_CODES.expiresAt
     *
     * @param expiresAt the value for OTP_SMS_CODES.expiresAt
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setExpiresAt(Date expiresAt) {
        this.expiresAt = expiresAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OTP_SMS_CODES.status
     *
     * @return the value of OTP_SMS_CODES.status
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OTP_SMS_CODES.status
     *
     * @param status the value for OTP_SMS_CODES.status
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }
}