package com.ticnow.security.model.admin;

public class ProfileUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROFILE_USER.id_profile_user
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id_profile_user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROFILE_USER.id_state
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id_state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROFILE_USER.id_viser
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id_viser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROFILE_USER.profile_name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String profile_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROFILE_USER.description_profile
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String description_profile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROFILE_USER.external
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Byte external;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROFILE_USER.institution_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Long institution_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROFILE_USER.id_profile_user
     *
     * @return the value of PROFILE_USER.id_profile_user
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId_profile_user() {
        return id_profile_user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROFILE_USER.id_profile_user
     *
     * @param id_profile_user the value for PROFILE_USER.id_profile_user
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId_profile_user(Integer id_profile_user) {
        this.id_profile_user = id_profile_user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROFILE_USER.id_state
     *
     * @return the value of PROFILE_USER.id_state
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId_state() {
        return id_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROFILE_USER.id_state
     *
     * @param id_state the value for PROFILE_USER.id_state
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId_state(Integer id_state) {
        this.id_state = id_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROFILE_USER.id_viser
     *
     * @return the value of PROFILE_USER.id_viser
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId_viser() {
        return id_viser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROFILE_USER.id_viser
     *
     * @param id_viser the value for PROFILE_USER.id_viser
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId_viser(Integer id_viser) {
        this.id_viser = id_viser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROFILE_USER.profile_name
     *
     * @return the value of PROFILE_USER.profile_name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getProfile_name() {
        return profile_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROFILE_USER.profile_name
     *
     * @param profile_name the value for PROFILE_USER.profile_name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setProfile_name(String profile_name) {
        this.profile_name = profile_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROFILE_USER.description_profile
     *
     * @return the value of PROFILE_USER.description_profile
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getDescription_profile() {
        return description_profile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROFILE_USER.description_profile
     *
     * @param description_profile the value for PROFILE_USER.description_profile
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setDescription_profile(String description_profile) {
        this.description_profile = description_profile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROFILE_USER.external
     *
     * @return the value of PROFILE_USER.external
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Byte getExternal() {
        return external;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROFILE_USER.external
     *
     * @param external the value for PROFILE_USER.external
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setExternal(Byte external) {
        this.external = external;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROFILE_USER.institution_id
     *
     * @return the value of PROFILE_USER.institution_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Long getInstitution_id() {
        return institution_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROFILE_USER.institution_id
     *
     * @param institution_id the value for PROFILE_USER.institution_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setInstitution_id(Long institution_id) {
        this.institution_id = institution_id;
    }
}