package com.ticnow.security.model.admin;

public class Risk {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RISK.id_risk
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id_risk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RISK.id_risk_level
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id_risk_level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RISK.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RISK.engine_code
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String engine_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RISK.start_range
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer start_range;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RISK.end_range
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer end_range;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RISK.id_risk
     *
     * @return the value of RISK.id_risk
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId_risk() {
        return id_risk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RISK.id_risk
     *
     * @param id_risk the value for RISK.id_risk
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId_risk(Integer id_risk) {
        this.id_risk = id_risk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RISK.id_risk_level
     *
     * @return the value of RISK.id_risk_level
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId_risk_level() {
        return id_risk_level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RISK.id_risk_level
     *
     * @param id_risk_level the value for RISK.id_risk_level
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId_risk_level(Integer id_risk_level) {
        this.id_risk_level = id_risk_level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RISK.id
     *
     * @return the value of RISK.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RISK.id
     *
     * @param id the value for RISK.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RISK.engine_code
     *
     * @return the value of RISK.engine_code
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getEngine_code() {
        return engine_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RISK.engine_code
     *
     * @param engine_code the value for RISK.engine_code
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setEngine_code(String engine_code) {
        this.engine_code = engine_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RISK.start_range
     *
     * @return the value of RISK.start_range
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getStart_range() {
        return start_range;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RISK.start_range
     *
     * @param start_range the value for RISK.start_range
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setStart_range(Integer start_range) {
        this.start_range = start_range;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RISK.end_range
     *
     * @return the value of RISK.end_range
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getEnd_range() {
        return end_range;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RISK.end_range
     *
     * @param end_range the value for RISK.end_range
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setEnd_range(Integer end_range) {
        this.end_range = end_range;
    }
}