package com.ticnow.security.model.admin;

public class RiskEngineConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RISK_ENGINE_CONFIG.URL
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String URL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RISK_ENGINE_CONFIG.name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RISK_ENGINE_CONFIG.learningMode
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Boolean learningMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RISK_ENGINE_CONFIG.actionOnTimeOut
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String actionOnTimeOut;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RISK_ENGINE_CONFIG.actionOnError
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String actionOnError;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RISK_ENGINE_CONFIG.timeout
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String timeout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RISK_ENGINE_CONFIG.activateSmsNotification
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Boolean activateSmsNotification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RISK_ENGINE_CONFIG.activateEmailNotification
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Boolean activateEmailNotification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RISK_ENGINE_CONFIG.notificationLevelRisk
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String notificationLevelRisk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RISK_ENGINE_CONFIG.institution_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Long institution_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RISK_ENGINE_CONFIG.URL
     *
     * @return the value of RISK_ENGINE_CONFIG.URL
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getURL() {
        return URL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RISK_ENGINE_CONFIG.URL
     *
     * @param URL the value for RISK_ENGINE_CONFIG.URL
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setURL(String URL) {
        this.URL = URL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RISK_ENGINE_CONFIG.name
     *
     * @return the value of RISK_ENGINE_CONFIG.name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RISK_ENGINE_CONFIG.name
     *
     * @param name the value for RISK_ENGINE_CONFIG.name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RISK_ENGINE_CONFIG.learningMode
     *
     * @return the value of RISK_ENGINE_CONFIG.learningMode
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Boolean getLearningMode() {
        return learningMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RISK_ENGINE_CONFIG.learningMode
     *
     * @param learningMode the value for RISK_ENGINE_CONFIG.learningMode
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setLearningMode(Boolean learningMode) {
        this.learningMode = learningMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RISK_ENGINE_CONFIG.actionOnTimeOut
     *
     * @return the value of RISK_ENGINE_CONFIG.actionOnTimeOut
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getActionOnTimeOut() {
        return actionOnTimeOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RISK_ENGINE_CONFIG.actionOnTimeOut
     *
     * @param actionOnTimeOut the value for RISK_ENGINE_CONFIG.actionOnTimeOut
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setActionOnTimeOut(String actionOnTimeOut) {
        this.actionOnTimeOut = actionOnTimeOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RISK_ENGINE_CONFIG.actionOnError
     *
     * @return the value of RISK_ENGINE_CONFIG.actionOnError
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getActionOnError() {
        return actionOnError;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RISK_ENGINE_CONFIG.actionOnError
     *
     * @param actionOnError the value for RISK_ENGINE_CONFIG.actionOnError
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setActionOnError(String actionOnError) {
        this.actionOnError = actionOnError;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RISK_ENGINE_CONFIG.timeout
     *
     * @return the value of RISK_ENGINE_CONFIG.timeout
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getTimeout() {
        return timeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RISK_ENGINE_CONFIG.timeout
     *
     * @param timeout the value for RISK_ENGINE_CONFIG.timeout
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setTimeout(String timeout) {
        this.timeout = timeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RISK_ENGINE_CONFIG.activateSmsNotification
     *
     * @return the value of RISK_ENGINE_CONFIG.activateSmsNotification
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Boolean getActivateSmsNotification() {
        return activateSmsNotification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RISK_ENGINE_CONFIG.activateSmsNotification
     *
     * @param activateSmsNotification the value for RISK_ENGINE_CONFIG.activateSmsNotification
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setActivateSmsNotification(Boolean activateSmsNotification) {
        this.activateSmsNotification = activateSmsNotification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RISK_ENGINE_CONFIG.activateEmailNotification
     *
     * @return the value of RISK_ENGINE_CONFIG.activateEmailNotification
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Boolean getActivateEmailNotification() {
        return activateEmailNotification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RISK_ENGINE_CONFIG.activateEmailNotification
     *
     * @param activateEmailNotification the value for RISK_ENGINE_CONFIG.activateEmailNotification
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setActivateEmailNotification(Boolean activateEmailNotification) {
        this.activateEmailNotification = activateEmailNotification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RISK_ENGINE_CONFIG.notificationLevelRisk
     *
     * @return the value of RISK_ENGINE_CONFIG.notificationLevelRisk
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getNotificationLevelRisk() {
        return notificationLevelRisk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RISK_ENGINE_CONFIG.notificationLevelRisk
     *
     * @param notificationLevelRisk the value for RISK_ENGINE_CONFIG.notificationLevelRisk
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setNotificationLevelRisk(String notificationLevelRisk) {
        this.notificationLevelRisk = notificationLevelRisk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RISK_ENGINE_CONFIG.institution_id
     *
     * @return the value of RISK_ENGINE_CONFIG.institution_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Long getInstitution_id() {
        return institution_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RISK_ENGINE_CONFIG.institution_id
     *
     * @param institution_id the value for RISK_ENGINE_CONFIG.institution_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setInstitution_id(Long institution_id) {
        this.institution_id = institution_id;
    }
}