package com.ticnow.security.model.admin;

public class ServicesIntegration {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SERVICES_INTEGRATION.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SERVICES_INTEGRATION.serviceName
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String serviceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SERVICES_INTEGRATION.serviceEndpoint
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String serviceEndpoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SERVICES_INTEGRATION.serviceEchoTest
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String serviceEchoTest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SERVICES_INTEGRATION.serviceTimeOut
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer serviceTimeOut;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SERVICES_INTEGRATION.backend
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String backend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SERVICES_INTEGRATION.status
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SERVICES_INTEGRATION.institution_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Long institution_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SERVICES_INTEGRATION.methodAction
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String methodAction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SERVICES_INTEGRATION.id
     *
     * @return the value of SERVICES_INTEGRATION.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SERVICES_INTEGRATION.id
     *
     * @param id the value for SERVICES_INTEGRATION.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SERVICES_INTEGRATION.serviceName
     *
     * @return the value of SERVICES_INTEGRATION.serviceName
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SERVICES_INTEGRATION.serviceName
     *
     * @param serviceName the value for SERVICES_INTEGRATION.serviceName
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SERVICES_INTEGRATION.serviceEndpoint
     *
     * @return the value of SERVICES_INTEGRATION.serviceEndpoint
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getServiceEndpoint() {
        return serviceEndpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SERVICES_INTEGRATION.serviceEndpoint
     *
     * @param serviceEndpoint the value for SERVICES_INTEGRATION.serviceEndpoint
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setServiceEndpoint(String serviceEndpoint) {
        this.serviceEndpoint = serviceEndpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SERVICES_INTEGRATION.serviceEchoTest
     *
     * @return the value of SERVICES_INTEGRATION.serviceEchoTest
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getServiceEchoTest() {
        return serviceEchoTest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SERVICES_INTEGRATION.serviceEchoTest
     *
     * @param serviceEchoTest the value for SERVICES_INTEGRATION.serviceEchoTest
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setServiceEchoTest(String serviceEchoTest) {
        this.serviceEchoTest = serviceEchoTest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SERVICES_INTEGRATION.serviceTimeOut
     *
     * @return the value of SERVICES_INTEGRATION.serviceTimeOut
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getServiceTimeOut() {
        return serviceTimeOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SERVICES_INTEGRATION.serviceTimeOut
     *
     * @param serviceTimeOut the value for SERVICES_INTEGRATION.serviceTimeOut
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setServiceTimeOut(Integer serviceTimeOut) {
        this.serviceTimeOut = serviceTimeOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SERVICES_INTEGRATION.backend
     *
     * @return the value of SERVICES_INTEGRATION.backend
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getBackend() {
        return backend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SERVICES_INTEGRATION.backend
     *
     * @param backend the value for SERVICES_INTEGRATION.backend
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setBackend(String backend) {
        this.backend = backend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SERVICES_INTEGRATION.status
     *
     * @return the value of SERVICES_INTEGRATION.status
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SERVICES_INTEGRATION.status
     *
     * @param status the value for SERVICES_INTEGRATION.status
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SERVICES_INTEGRATION.institution_id
     *
     * @return the value of SERVICES_INTEGRATION.institution_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Long getInstitution_id() {
        return institution_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SERVICES_INTEGRATION.institution_id
     *
     * @param institution_id the value for SERVICES_INTEGRATION.institution_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setInstitution_id(Long institution_id) {
        this.institution_id = institution_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SERVICES_INTEGRATION.methodAction
     *
     * @return the value of SERVICES_INTEGRATION.methodAction
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getMethodAction() {
        return methodAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SERVICES_INTEGRATION.methodAction
     *
     * @param methodAction the value for SERVICES_INTEGRATION.methodAction
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setMethodAction(String methodAction) {
        this.methodAction = methodAction;
    }
}