package com.ticnow.security.model.admin;

public class TransactionDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRANSACTION_DETAIL.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRANSACTION_DETAIL.uuid
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRANSACTION_DETAIL.userDestinyName
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String userDestinyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRANSACTION_DETAIL.userDestinySsn
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String userDestinySsn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRANSACTION_DETAIL.subject
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRANSACTION_DETAIL.accountDestiny
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String accountDestiny;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRANSACTION_DETAIL.amount
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRANSACTION_DETAIL.bankDestiny
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String bankDestiny;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRANSACTION_DETAIL.recurrent
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Boolean recurrent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRANSACTION_DETAIL.suspicius
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Boolean suspicius;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRANSACTION_DETAIL.transaction_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer transaction_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRANSACTION_DETAIL.accountOrigin
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String accountOrigin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRANSACTION_DETAIL.currency
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRANSACTION_DETAIL.accountType
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String accountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRANSACTION_DETAIL.serviceName
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String serviceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRANSACTION_DETAIL.bankOrigin
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String bankOrigin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRANSACTION_DETAIL.serviceCode
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String serviceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRANSACTION_DETAIL.serviceId
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String serviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRANSACTION_DETAIL.serviceType
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String serviceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRANSACTION_DETAIL.invoiceNum
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String invoiceNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRANSACTION_DETAIL.paymentDate
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String paymentDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRANSACTION_DETAIL.id
     *
     * @return the value of TRANSACTION_DETAIL.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRANSACTION_DETAIL.id
     *
     * @param id the value for TRANSACTION_DETAIL.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRANSACTION_DETAIL.uuid
     *
     * @return the value of TRANSACTION_DETAIL.uuid
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRANSACTION_DETAIL.uuid
     *
     * @param uuid the value for TRANSACTION_DETAIL.uuid
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRANSACTION_DETAIL.userDestinyName
     *
     * @return the value of TRANSACTION_DETAIL.userDestinyName
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getUserDestinyName() {
        return userDestinyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRANSACTION_DETAIL.userDestinyName
     *
     * @param userDestinyName the value for TRANSACTION_DETAIL.userDestinyName
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setUserDestinyName(String userDestinyName) {
        this.userDestinyName = userDestinyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRANSACTION_DETAIL.userDestinySsn
     *
     * @return the value of TRANSACTION_DETAIL.userDestinySsn
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getUserDestinySsn() {
        return userDestinySsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRANSACTION_DETAIL.userDestinySsn
     *
     * @param userDestinySsn the value for TRANSACTION_DETAIL.userDestinySsn
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setUserDestinySsn(String userDestinySsn) {
        this.userDestinySsn = userDestinySsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRANSACTION_DETAIL.subject
     *
     * @return the value of TRANSACTION_DETAIL.subject
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRANSACTION_DETAIL.subject
     *
     * @param subject the value for TRANSACTION_DETAIL.subject
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRANSACTION_DETAIL.accountDestiny
     *
     * @return the value of TRANSACTION_DETAIL.accountDestiny
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getAccountDestiny() {
        return accountDestiny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRANSACTION_DETAIL.accountDestiny
     *
     * @param accountDestiny the value for TRANSACTION_DETAIL.accountDestiny
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setAccountDestiny(String accountDestiny) {
        this.accountDestiny = accountDestiny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRANSACTION_DETAIL.amount
     *
     * @return the value of TRANSACTION_DETAIL.amount
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRANSACTION_DETAIL.amount
     *
     * @param amount the value for TRANSACTION_DETAIL.amount
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setAmount(String amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRANSACTION_DETAIL.bankDestiny
     *
     * @return the value of TRANSACTION_DETAIL.bankDestiny
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getBankDestiny() {
        return bankDestiny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRANSACTION_DETAIL.bankDestiny
     *
     * @param bankDestiny the value for TRANSACTION_DETAIL.bankDestiny
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setBankDestiny(String bankDestiny) {
        this.bankDestiny = bankDestiny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRANSACTION_DETAIL.recurrent
     *
     * @return the value of TRANSACTION_DETAIL.recurrent
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Boolean getRecurrent() {
        return recurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRANSACTION_DETAIL.recurrent
     *
     * @param recurrent the value for TRANSACTION_DETAIL.recurrent
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setRecurrent(Boolean recurrent) {
        this.recurrent = recurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRANSACTION_DETAIL.suspicius
     *
     * @return the value of TRANSACTION_DETAIL.suspicius
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Boolean getSuspicius() {
        return suspicius;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRANSACTION_DETAIL.suspicius
     *
     * @param suspicius the value for TRANSACTION_DETAIL.suspicius
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setSuspicius(Boolean suspicius) {
        this.suspicius = suspicius;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRANSACTION_DETAIL.transaction_id
     *
     * @return the value of TRANSACTION_DETAIL.transaction_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getTransaction_id() {
        return transaction_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRANSACTION_DETAIL.transaction_id
     *
     * @param transaction_id the value for TRANSACTION_DETAIL.transaction_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setTransaction_id(Integer transaction_id) {
        this.transaction_id = transaction_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRANSACTION_DETAIL.accountOrigin
     *
     * @return the value of TRANSACTION_DETAIL.accountOrigin
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getAccountOrigin() {
        return accountOrigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRANSACTION_DETAIL.accountOrigin
     *
     * @param accountOrigin the value for TRANSACTION_DETAIL.accountOrigin
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setAccountOrigin(String accountOrigin) {
        this.accountOrigin = accountOrigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRANSACTION_DETAIL.currency
     *
     * @return the value of TRANSACTION_DETAIL.currency
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRANSACTION_DETAIL.currency
     *
     * @param currency the value for TRANSACTION_DETAIL.currency
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRANSACTION_DETAIL.accountType
     *
     * @return the value of TRANSACTION_DETAIL.accountType
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRANSACTION_DETAIL.accountType
     *
     * @param accountType the value for TRANSACTION_DETAIL.accountType
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRANSACTION_DETAIL.serviceName
     *
     * @return the value of TRANSACTION_DETAIL.serviceName
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRANSACTION_DETAIL.serviceName
     *
     * @param serviceName the value for TRANSACTION_DETAIL.serviceName
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRANSACTION_DETAIL.bankOrigin
     *
     * @return the value of TRANSACTION_DETAIL.bankOrigin
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getBankOrigin() {
        return bankOrigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRANSACTION_DETAIL.bankOrigin
     *
     * @param bankOrigin the value for TRANSACTION_DETAIL.bankOrigin
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setBankOrigin(String bankOrigin) {
        this.bankOrigin = bankOrigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRANSACTION_DETAIL.serviceCode
     *
     * @return the value of TRANSACTION_DETAIL.serviceCode
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getServiceCode() {
        return serviceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRANSACTION_DETAIL.serviceCode
     *
     * @param serviceCode the value for TRANSACTION_DETAIL.serviceCode
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setServiceCode(String serviceCode) {
        this.serviceCode = serviceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRANSACTION_DETAIL.serviceId
     *
     * @return the value of TRANSACTION_DETAIL.serviceId
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRANSACTION_DETAIL.serviceId
     *
     * @param serviceId the value for TRANSACTION_DETAIL.serviceId
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setServiceId(String serviceId) {
        this.serviceId = serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRANSACTION_DETAIL.serviceType
     *
     * @return the value of TRANSACTION_DETAIL.serviceType
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getServiceType() {
        return serviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRANSACTION_DETAIL.serviceType
     *
     * @param serviceType the value for TRANSACTION_DETAIL.serviceType
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setServiceType(String serviceType) {
        this.serviceType = serviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRANSACTION_DETAIL.invoiceNum
     *
     * @return the value of TRANSACTION_DETAIL.invoiceNum
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getInvoiceNum() {
        return invoiceNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRANSACTION_DETAIL.invoiceNum
     *
     * @param invoiceNum the value for TRANSACTION_DETAIL.invoiceNum
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setInvoiceNum(String invoiceNum) {
        this.invoiceNum = invoiceNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRANSACTION_DETAIL.paymentDate
     *
     * @return the value of TRANSACTION_DETAIL.paymentDate
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getPaymentDate() {
        return paymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRANSACTION_DETAIL.paymentDate
     *
     * @param paymentDate the value for TRANSACTION_DETAIL.paymentDate
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setPaymentDate(String paymentDate) {
        this.paymentDate = paymentDate;
    }
}