package com.ticnow.security.model.admin;

import java.util.Date;

public class Transaction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRANSACTION.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRANSACTION.uuid
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRANSACTION.transactionType
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String transactionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRANSACTION.transactionChannel
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String transactionChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRANSACTION.initTransaction
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Date initTransaction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRANSACTION.authMethod
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String authMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRANSACTION.status
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRANSACTION.user_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRANSACTION.updateTransaction
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Date updateTransaction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRANSACTION.uuidDevice
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String uuidDevice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRANSACTION.subTypeTransaction
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String subTypeTransaction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRANSACTION.id
     *
     * @return the value of TRANSACTION.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRANSACTION.id
     *
     * @param id the value for TRANSACTION.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRANSACTION.uuid
     *
     * @return the value of TRANSACTION.uuid
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRANSACTION.uuid
     *
     * @param uuid the value for TRANSACTION.uuid
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRANSACTION.transactionType
     *
     * @return the value of TRANSACTION.transactionType
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getTransactionType() {
        return transactionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRANSACTION.transactionType
     *
     * @param transactionType the value for TRANSACTION.transactionType
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRANSACTION.transactionChannel
     *
     * @return the value of TRANSACTION.transactionChannel
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getTransactionChannel() {
        return transactionChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRANSACTION.transactionChannel
     *
     * @param transactionChannel the value for TRANSACTION.transactionChannel
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setTransactionChannel(String transactionChannel) {
        this.transactionChannel = transactionChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRANSACTION.initTransaction
     *
     * @return the value of TRANSACTION.initTransaction
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Date getInitTransaction() {
        return initTransaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRANSACTION.initTransaction
     *
     * @param initTransaction the value for TRANSACTION.initTransaction
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setInitTransaction(Date initTransaction) {
        this.initTransaction = initTransaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRANSACTION.authMethod
     *
     * @return the value of TRANSACTION.authMethod
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getAuthMethod() {
        return authMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRANSACTION.authMethod
     *
     * @param authMethod the value for TRANSACTION.authMethod
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setAuthMethod(String authMethod) {
        this.authMethod = authMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRANSACTION.status
     *
     * @return the value of TRANSACTION.status
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRANSACTION.status
     *
     * @param status the value for TRANSACTION.status
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRANSACTION.user_id
     *
     * @return the value of TRANSACTION.user_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRANSACTION.user_id
     *
     * @param user_id the value for TRANSACTION.user_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRANSACTION.updateTransaction
     *
     * @return the value of TRANSACTION.updateTransaction
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Date getUpdateTransaction() {
        return updateTransaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRANSACTION.updateTransaction
     *
     * @param updateTransaction the value for TRANSACTION.updateTransaction
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setUpdateTransaction(Date updateTransaction) {
        this.updateTransaction = updateTransaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRANSACTION.uuidDevice
     *
     * @return the value of TRANSACTION.uuidDevice
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getUuidDevice() {
        return uuidDevice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRANSACTION.uuidDevice
     *
     * @param uuidDevice the value for TRANSACTION.uuidDevice
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setUuidDevice(String uuidDevice) {
        this.uuidDevice = uuidDevice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRANSACTION.subTypeTransaction
     *
     * @return the value of TRANSACTION.subTypeTransaction
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getSubTypeTransaction() {
        return subTypeTransaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRANSACTION.subTypeTransaction
     *
     * @param subTypeTransaction the value for TRANSACTION.subTypeTransaction
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setSubTypeTransaction(String subTypeTransaction) {
        this.subTypeTransaction = subTypeTransaction;
    }
}