package com.ticnow.security.model.admin;

public class TypeMessages {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TYPE_MESSAGES.id_type_message
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id_type_message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TYPE_MESSAGES.description_type_message
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String description_type_message;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TYPE_MESSAGES.id_type_message
     *
     * @return the value of TYPE_MESSAGES.id_type_message
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId_type_message() {
        return id_type_message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TYPE_MESSAGES.id_type_message
     *
     * @param id_type_message the value for TYPE_MESSAGES.id_type_message
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId_type_message(Integer id_type_message) {
        this.id_type_message = id_type_message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TYPE_MESSAGES.description_type_message
     *
     * @return the value of TYPE_MESSAGES.description_type_message
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getDescription_type_message() {
        return description_type_message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TYPE_MESSAGES.description_type_message
     *
     * @param description_type_message the value for TYPE_MESSAGES.description_type_message
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setDescription_type_message(String description_type_message) {
        this.description_type_message = description_type_message;
    }
}