package com.ticnow.security.model.admin;

import java.util.Date;

public class UserClient {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_CLIENT.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_CLIENT.real_name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String real_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_CLIENT.enrollment_date
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Date enrollment_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_CLIENT.status
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_CLIENT.ssn
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String ssn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_CLIENT.institution_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Long institution_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_CLIENT.surnames
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String surnames;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_CLIENT.birth_date
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Date birth_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_CLIENT.minimal_enroll_scoring
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Double minimal_enroll_scoring;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_CLIENT.minimal_transaction_scoring
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Double minimal_transaction_scoring;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_CLIENT.segment_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Integer segment_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_CLIENT.user_person_uuid
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private String user_person_uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_CLIENT.enroll_definition_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    private Long enroll_definition_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_CLIENT.id
     *
     * @return the value of USER_CLIENT.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_CLIENT.id
     *
     * @param id the value for USER_CLIENT.id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_CLIENT.real_name
     *
     * @return the value of USER_CLIENT.real_name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getReal_name() {
        return real_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_CLIENT.real_name
     *
     * @param real_name the value for USER_CLIENT.real_name
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setReal_name(String real_name) {
        this.real_name = real_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_CLIENT.enrollment_date
     *
     * @return the value of USER_CLIENT.enrollment_date
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Date getEnrollment_date() {
        return enrollment_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_CLIENT.enrollment_date
     *
     * @param enrollment_date the value for USER_CLIENT.enrollment_date
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setEnrollment_date(Date enrollment_date) {
        this.enrollment_date = enrollment_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_CLIENT.status
     *
     * @return the value of USER_CLIENT.status
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_CLIENT.status
     *
     * @param status the value for USER_CLIENT.status
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_CLIENT.ssn
     *
     * @return the value of USER_CLIENT.ssn
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getSsn() {
        return ssn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_CLIENT.ssn
     *
     * @param ssn the value for USER_CLIENT.ssn
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setSsn(String ssn) {
        this.ssn = ssn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_CLIENT.institution_id
     *
     * @return the value of USER_CLIENT.institution_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Long getInstitution_id() {
        return institution_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_CLIENT.institution_id
     *
     * @param institution_id the value for USER_CLIENT.institution_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setInstitution_id(Long institution_id) {
        this.institution_id = institution_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_CLIENT.surnames
     *
     * @return the value of USER_CLIENT.surnames
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getSurnames() {
        return surnames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_CLIENT.surnames
     *
     * @param surnames the value for USER_CLIENT.surnames
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setSurnames(String surnames) {
        this.surnames = surnames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_CLIENT.birth_date
     *
     * @return the value of USER_CLIENT.birth_date
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Date getBirth_date() {
        return birth_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_CLIENT.birth_date
     *
     * @param birth_date the value for USER_CLIENT.birth_date
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setBirth_date(Date birth_date) {
        this.birth_date = birth_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_CLIENT.minimal_enroll_scoring
     *
     * @return the value of USER_CLIENT.minimal_enroll_scoring
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Double getMinimal_enroll_scoring() {
        return minimal_enroll_scoring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_CLIENT.minimal_enroll_scoring
     *
     * @param minimal_enroll_scoring the value for USER_CLIENT.minimal_enroll_scoring
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setMinimal_enroll_scoring(Double minimal_enroll_scoring) {
        this.minimal_enroll_scoring = minimal_enroll_scoring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_CLIENT.minimal_transaction_scoring
     *
     * @return the value of USER_CLIENT.minimal_transaction_scoring
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Double getMinimal_transaction_scoring() {
        return minimal_transaction_scoring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_CLIENT.minimal_transaction_scoring
     *
     * @param minimal_transaction_scoring the value for USER_CLIENT.minimal_transaction_scoring
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setMinimal_transaction_scoring(Double minimal_transaction_scoring) {
        this.minimal_transaction_scoring = minimal_transaction_scoring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_CLIENT.segment_id
     *
     * @return the value of USER_CLIENT.segment_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Integer getSegment_id() {
        return segment_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_CLIENT.segment_id
     *
     * @param segment_id the value for USER_CLIENT.segment_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setSegment_id(Integer segment_id) {
        this.segment_id = segment_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_CLIENT.user_person_uuid
     *
     * @return the value of USER_CLIENT.user_person_uuid
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public String getUser_person_uuid() {
        return user_person_uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_CLIENT.user_person_uuid
     *
     * @param user_person_uuid the value for USER_CLIENT.user_person_uuid
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setUser_person_uuid(String user_person_uuid) {
        this.user_person_uuid = user_person_uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_CLIENT.enroll_definition_id
     *
     * @return the value of USER_CLIENT.enroll_definition_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public Long getEnroll_definition_id() {
        return enroll_definition_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_CLIENT.enroll_definition_id
     *
     * @param enroll_definition_id the value for USER_CLIENT.enroll_definition_id
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    public void setEnroll_definition_id(Long enroll_definition_id) {
        this.enroll_definition_id = enroll_definition_id;
    }
}