package com.ticnow.security.idnow.admin.persistence.mappers;

import com.ticnow.security.model.admin.Alerts;

public interface AlertsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALERTS
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int deleteByPrimaryKey(Integer id_alert);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALERTS
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insert(Alerts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALERTS
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insertSelective(Alerts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALERTS
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    Alerts selectByPrimaryKey(Integer id_alert);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALERTS
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKeySelective(Alerts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALERTS
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKey(Alerts record);
}