package com.ticnow.security.idnow.admin.persistence.mappers;

import com.ticnow.security.model.admin.AnalizeTransactionDetail;

public interface AnalizeTransactionDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ANALIZE_TRANSACTION_DETAIL
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ANALIZE_TRANSACTION_DETAIL
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insert(AnalizeTransactionDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ANALIZE_TRANSACTION_DETAIL
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insertSelective(AnalizeTransactionDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ANALIZE_TRANSACTION_DETAIL
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    AnalizeTransactionDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ANALIZE_TRANSACTION_DETAIL
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKeySelective(AnalizeTransactionDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ANALIZE_TRANSACTION_DETAIL
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKeyWithBLOBs(AnalizeTransactionDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ANALIZE_TRANSACTION_DETAIL
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKey(AnalizeTransactionDetail record);
}