package com.ticnow.security.idnow.admin.persistence.mappers;

import com.ticnow.security.model.admin.AnalizeTransaction;

public interface AnalizeTransactionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ANALIZE_TRANSACTION
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ANALIZE_TRANSACTION
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insert(AnalizeTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ANALIZE_TRANSACTION
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insertSelective(AnalizeTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ANALIZE_TRANSACTION
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    AnalizeTransaction selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ANALIZE_TRANSACTION
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKeySelective(AnalizeTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ANALIZE_TRANSACTION
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKey(AnalizeTransaction record);
}