package com.ticnow.security.idnow.admin.persistence.mappers;

import com.ticnow.security.model.admin.AuditLog;

public interface AuditLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUDIT_LOG
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUDIT_LOG
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insert(AuditLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUDIT_LOG
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insertSelective(AuditLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUDIT_LOG
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    AuditLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUDIT_LOG
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKeySelective(AuditLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUDIT_LOG
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKey(AuditLog record);
}