package com.ticnow.security.idnow.admin.persistence.mappers;

import com.ticnow.security.model.admin.Authenticators;

public interface AuthenticatorsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHENTICATORS
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHENTICATORS
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insert(Authenticators record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHENTICATORS
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insertSelective(Authenticators record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHENTICATORS
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    Authenticators selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHENTICATORS
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKeySelective(Authenticators record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHENTICATORS
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKey(Authenticators record);
}