package com.ticnow.security.idnow.admin.persistence.mappers;

import com.ticnow.security.model.admin.ChannelStates;

public interface ChannelStatesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHANNEL_STATES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int deleteByPrimaryKey(Integer id_channel_states);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHANNEL_STATES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insert(ChannelStates record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHANNEL_STATES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insertSelective(ChannelStates record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHANNEL_STATES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    ChannelStates selectByPrimaryKey(Integer id_channel_states);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHANNEL_STATES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKeySelective(ChannelStates record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHANNEL_STATES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKey(ChannelStates record);
}