package com.ticnow.security.idnow.admin.persistence.mappers;

import com.ticnow.security.model.admin.DeviceCredentials;

public interface DeviceCredentialsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVICE_CREDENTIALS
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insert(DeviceCredentials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVICE_CREDENTIALS
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insertSelective(DeviceCredentials record);
}