package com.ticnow.security.idnow.admin.persistence.mappers;

import com.ticnow.security.model.admin.EnrollSmsCodes;

public interface EnrollSmsCodesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENROLL_SMS_CODES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENROLL_SMS_CODES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insert(EnrollSmsCodes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENROLL_SMS_CODES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insertSelective(EnrollSmsCodes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENROLL_SMS_CODES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    EnrollSmsCodes selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENROLL_SMS_CODES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKeySelective(EnrollSmsCodes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENROLL_SMS_CODES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKey(EnrollSmsCodes record);
}