package com.ticnow.security.idnow.admin.persistence.mappers;

import com.ticnow.security.model.admin.InstitutionExternalChallenges;

public interface InstitutionExternalChallengesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSTITUTION_EXTERNAL_CHALLENGES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSTITUTION_EXTERNAL_CHALLENGES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insert(InstitutionExternalChallenges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSTITUTION_EXTERNAL_CHALLENGES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insertSelective(InstitutionExternalChallenges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSTITUTION_EXTERNAL_CHALLENGES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    InstitutionExternalChallenges selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSTITUTION_EXTERNAL_CHALLENGES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKeySelective(InstitutionExternalChallenges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSTITUTION_EXTERNAL_CHALLENGES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKey(InstitutionExternalChallenges record);
}