package com.ticnow.security.idnow.admin.persistence.mappers;

import com.ticnow.security.model.admin.InstitutionTransaction;

public interface InstitutionTransactionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSTITUTION_TRANSACTION
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int deleteByPrimaryKey(Long id_institution_transaction);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSTITUTION_TRANSACTION
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insert(InstitutionTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSTITUTION_TRANSACTION
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insertSelective(InstitutionTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSTITUTION_TRANSACTION
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    InstitutionTransaction selectByPrimaryKey(Long id_institution_transaction);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSTITUTION_TRANSACTION
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKeySelective(InstitutionTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSTITUTION_TRANSACTION
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKey(InstitutionTransaction record);
}