package com.ticnow.security.idnow.admin.persistence.mappers;

import com.ticnow.security.model.admin.InstitutionAuthenticators;

public interface InstitutionAuthenticatorsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSTITUTION_AUTHENTICATORS
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSTITUTION_AUTHENTICATORS
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insert(InstitutionAuthenticators record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSTITUTION_AUTHENTICATORS
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insertSelective(InstitutionAuthenticators record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSTITUTION_AUTHENTICATORS
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    InstitutionAuthenticators selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSTITUTION_AUTHENTICATORS
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKeySelective(InstitutionAuthenticators record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSTITUTION_AUTHENTICATORS
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKey(InstitutionAuthenticators record);
}