package com.ticnow.security.idnow.admin.persistence.mappers;

import com.ticnow.security.model.admin.LoginUser;

public interface LoginUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGIN_USER
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int deleteByPrimaryKey(Integer id_login_user);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGIN_USER
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insert(LoginUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGIN_USER
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insertSelective(LoginUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGIN_USER
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    LoginUser selectByPrimaryKey(Integer id_login_user);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGIN_USER
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKeySelective(LoginUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGIN_USER
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKey(LoginUser record);
}