package com.ticnow.security.idnow.admin.persistence.mappers;

import com.ticnow.security.model.admin.Messages;

public interface MessagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MESSAGES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int deleteByPrimaryKey(Integer id_menssage);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MESSAGES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insert(Messages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MESSAGES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insertSelective(Messages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MESSAGES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    Messages selectByPrimaryKey(Integer id_menssage);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MESSAGES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKeySelective(Messages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MESSAGES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKey(Messages record);
}