package com.ticnow.security.idnow.admin.persistence.mappers;

import com.ticnow.security.model.admin.Modules;

public interface ModulesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MODULES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int deleteByPrimaryKey(Integer id_modules);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MODULES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insert(Modules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MODULES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insertSelective(Modules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MODULES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    Modules selectByPrimaryKey(Integer id_modules);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MODULES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKeySelective(Modules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MODULES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKey(Modules record);
}