package com.ticnow.security.idnow.admin.persistence.mappers;

import com.ticnow.security.model.admin.ModulesActions;

public interface ModulesActionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MODULES_ACTIONS
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int deleteByPrimaryKey(Integer id_module_action);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MODULES_ACTIONS
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insert(ModulesActions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MODULES_ACTIONS
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insertSelective(ModulesActions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MODULES_ACTIONS
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    ModulesActions selectByPrimaryKey(Integer id_module_action);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MODULES_ACTIONS
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKeySelective(ModulesActions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MODULES_ACTIONS
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKey(ModulesActions record);
}