package com.ticnow.security.idnow.admin.persistence.mappers;

import com.ticnow.security.model.admin.Nationality;

public interface NationalityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NATIONALITY
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NATIONALITY
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insert(Nationality record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NATIONALITY
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insertSelective(Nationality record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NATIONALITY
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    Nationality selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NATIONALITY
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKeySelective(Nationality record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NATIONALITY
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKey(Nationality record);
}