package com.ticnow.security.idnow.admin.persistence.mappers;

import com.ticnow.security.model.admin.ProfileUser;

public interface ProfileUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROFILE_USER
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int deleteByPrimaryKey(Integer id_profile_user);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROFILE_USER
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insert(ProfileUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROFILE_USER
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insertSelective(ProfileUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROFILE_USER
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    ProfileUser selectByPrimaryKey(Integer id_profile_user);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROFILE_USER
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKeySelective(ProfileUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROFILE_USER
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKey(ProfileUser record);
}