package com.ticnow.security.idnow.admin.persistence.mappers;

import com.ticnow.security.model.admin.RiskEngineConfig;

public interface RiskEngineConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RISK_ENGINE_CONFIG
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insert(RiskEngineConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RISK_ENGINE_CONFIG
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insertSelective(RiskEngineConfig record);
}