package com.ticnow.security.idnow.admin.persistence.mappers;

import com.ticnow.security.model.admin.ServicesIntegration;

public interface ServicesIntegrationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SERVICES_INTEGRATION
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SERVICES_INTEGRATION
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insert(ServicesIntegration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SERVICES_INTEGRATION
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insertSelective(ServicesIntegration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SERVICES_INTEGRATION
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    ServicesIntegration selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SERVICES_INTEGRATION
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKeySelective(ServicesIntegration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SERVICES_INTEGRATION
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKey(ServicesIntegration record);
}