package com.ticnow.security.idnow.admin.persistence.mappers;

import com.ticnow.security.model.admin.SystemTransactionLog;

public interface SystemTransactionLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_TRANSACTION_LOG
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_TRANSACTION_LOG
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insert(SystemTransactionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_TRANSACTION_LOG
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insertSelective(SystemTransactionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_TRANSACTION_LOG
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    SystemTransactionLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_TRANSACTION_LOG
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKeySelective(SystemTransactionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_TRANSACTION_LOG
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKeyWithBLOBs(SystemTransactionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_TRANSACTION_LOG
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKey(SystemTransactionLog record);
}