package com.ticnow.security.idnow.admin.persistence.mappers;

import com.ticnow.security.model.admin.TransactionDetail;

public interface TransactionDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRANSACTION_DETAIL
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRANSACTION_DETAIL
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insert(TransactionDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRANSACTION_DETAIL
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insertSelective(TransactionDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRANSACTION_DETAIL
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    TransactionDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRANSACTION_DETAIL
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKeySelective(TransactionDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRANSACTION_DETAIL
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKey(TransactionDetail record);
}