package com.ticnow.security.idnow.admin.persistence.mappers;

import com.ticnow.security.model.admin.TransactionsRulesStatsAdds;

public interface TransactionsRulesStatsAddsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRANSACTIONS_RULES_STATS_ADDS
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRANSACTIONS_RULES_STATS_ADDS
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insert(TransactionsRulesStatsAdds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRANSACTIONS_RULES_STATS_ADDS
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insertSelective(TransactionsRulesStatsAdds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRANSACTIONS_RULES_STATS_ADDS
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    TransactionsRulesStatsAdds selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRANSACTIONS_RULES_STATS_ADDS
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKeySelective(TransactionsRulesStatsAdds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRANSACTIONS_RULES_STATS_ADDS
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKey(TransactionsRulesStatsAdds record);
}