package com.ticnow.security.idnow.admin.persistence.mappers;

import com.ticnow.security.model.admin.TypeMessages;

public interface TypeMessagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TYPE_MESSAGES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int deleteByPrimaryKey(Integer id_type_message);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TYPE_MESSAGES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insert(TypeMessages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TYPE_MESSAGES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insertSelective(TypeMessages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TYPE_MESSAGES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    TypeMessages selectByPrimaryKey(Integer id_type_message);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TYPE_MESSAGES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKeySelective(TypeMessages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TYPE_MESSAGES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKey(TypeMessages record);
}