package com.ticnow.security.idnow.admin.persistence.mappers;

import com.ticnow.security.model.admin.UserRegistration;

public interface UserRegistrationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_REGISTRATION
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int deleteByPrimaryKey(Integer id_user_registration);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_REGISTRATION
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insert(UserRegistration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_REGISTRATION
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insertSelective(UserRegistration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_REGISTRATION
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    UserRegistration selectByPrimaryKey(Integer id_user_registration);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_REGISTRATION
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKeySelective(UserRegistration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_REGISTRATION
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKey(UserRegistration record);
}