package com.ticnow.security.idnow.admin.persistence.mappers;

import com.ticnow.security.model.admin.UserDevices;

public interface UserDevicesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_DEVICES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_DEVICES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insert(UserDevices record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_DEVICES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insertSelective(UserDevices record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_DEVICES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    UserDevices selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_DEVICES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKeySelective(UserDevices record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_DEVICES
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKey(UserDevices record);
}