package com.ticnow.security.idnow.admin.persistence.mappers;

import com.ticnow.security.model.admin.UserClientsAuths;

public interface UserClientsAuthsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_CLIENTS_AUTHS
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_CLIENTS_AUTHS
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insert(UserClientsAuths record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_CLIENTS_AUTHS
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insertSelective(UserClientsAuths record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_CLIENTS_AUTHS
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    UserClientsAuths selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_CLIENTS_AUTHS
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKeySelective(UserClientsAuths record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_CLIENTS_AUTHS
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKey(UserClientsAuths record);
}