package com.ticnow.security.idnow.admin.persistence.mappers;

import com.ticnow.security.model.admin.Viser;

public interface ViserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VISER
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int deleteByPrimaryKey(Integer id_viser);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VISER
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insert(Viser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VISER
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int insertSelective(Viser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VISER
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    Viser selectByPrimaryKey(Integer id_viser);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VISER
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKeySelective(Viser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VISER
     *
     * @mbggenerated Wed Mar 21 14:07:09 CLST 2018
     */
    int updateByPrimaryKey(Viser record);
}